// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.16.1
// source: unityctl/common.proto

package unityctl

import (
	snakecommon "git.17zjh.com/snake/snake_proto/snakecommon"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SnakeCoinDetailItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count  int64  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	MarkId int32  `protobuf:"varint,2,opt,name=mark_id,json=markId,proto3" json:"mark_id,omitempty"`
	From   string `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
}

func (x *SnakeCoinDetailItem) Reset() {
	*x = SnakeCoinDetailItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unityctl_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SnakeCoinDetailItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnakeCoinDetailItem) ProtoMessage() {}

func (x *SnakeCoinDetailItem) ProtoReflect() protoreflect.Message {
	mi := &file_unityctl_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnakeCoinDetailItem.ProtoReflect.Descriptor instead.
func (*SnakeCoinDetailItem) Descriptor() ([]byte, []int) {
	return file_unityctl_common_proto_rawDescGZIP(), []int{0}
}

func (x *SnakeCoinDetailItem) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *SnakeCoinDetailItem) GetMarkId() int32 {
	if x != nil {
		return x.MarkId
	}
	return 0
}

func (x *SnakeCoinDetailItem) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

type TaskInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	State int32 `protobuf:"varint,2,opt,name=state,proto3" json:"state,omitempty"`
	Ad    int64 `protobuf:"varint,3,opt,name=ad,proto3" json:"ad,omitempty"`
	Own   bool  `protobuf:"varint,4,opt,name=own,proto3" json:"own,omitempty"`
}

func (x *TaskInfo) Reset() {
	*x = TaskInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unityctl_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskInfo) ProtoMessage() {}

func (x *TaskInfo) ProtoReflect() protoreflect.Message {
	mi := &file_unityctl_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskInfo.ProtoReflect.Descriptor instead.
func (*TaskInfo) Descriptor() ([]byte, []int) {
	return file_unityctl_common_proto_rawDescGZIP(), []int{1}
}

func (x *TaskInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TaskInfo) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *TaskInfo) GetAd() int64 {
	if x != nil {
		return x.Ad
	}
	return 0
}

func (x *TaskInfo) GetOwn() bool {
	if x != nil {
		return x.Own
	}
	return false
}

type WebBanner struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Url string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *WebBanner) Reset() {
	*x = WebBanner{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unityctl_common_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebBanner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebBanner) ProtoMessage() {}

func (x *WebBanner) ProtoReflect() protoreflect.Message {
	mi := &file_unityctl_common_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebBanner.ProtoReflect.Descriptor instead.
func (*WebBanner) Descriptor() ([]byte, []int) {
	return file_unityctl_common_proto_rawDescGZIP(), []int{2}
}

func (x *WebBanner) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WebBanner) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type FloatingItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Num   int64 `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
	Add   int64 `protobuf:"varint,3,opt,name=add,proto3" json:"add,omitempty"`
	State int32 `protobuf:"varint,4,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *FloatingItem) Reset() {
	*x = FloatingItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unityctl_common_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FloatingItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FloatingItem) ProtoMessage() {}

func (x *FloatingItem) ProtoReflect() protoreflect.Message {
	mi := &file_unityctl_common_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FloatingItem.ProtoReflect.Descriptor instead.
func (*FloatingItem) Descriptor() ([]byte, []int) {
	return file_unityctl_common_proto_rawDescGZIP(), []int{3}
}

func (x *FloatingItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FloatingItem) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *FloatingItem) GetAdd() int64 {
	if x != nil {
		return x.Add
	}
	return 0
}

func (x *FloatingItem) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

type FloatingInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RewardList   []*snakecommon.CRewardItem `protobuf:"bytes,1,rep,name=reward_list,json=rewardList,proto3" json:"reward_list,omitempty"`
	RedDot       int32                      `protobuf:"varint,2,opt,name=red_dot,json=redDot,proto3" json:"red_dot,omitempty"`
	FloatingList []*FloatingItem            `protobuf:"bytes,3,rep,name=floating_list,json=floatingList,proto3" json:"floating_list,omitempty"`
}

func (x *FloatingInfo) Reset() {
	*x = FloatingInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unityctl_common_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FloatingInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FloatingInfo) ProtoMessage() {}

func (x *FloatingInfo) ProtoReflect() protoreflect.Message {
	mi := &file_unityctl_common_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FloatingInfo.ProtoReflect.Descriptor instead.
func (*FloatingInfo) Descriptor() ([]byte, []int) {
	return file_unityctl_common_proto_rawDescGZIP(), []int{4}
}

func (x *FloatingInfo) GetRewardList() []*snakecommon.CRewardItem {
	if x != nil {
		return x.RewardList
	}
	return nil
}

func (x *FloatingInfo) GetRedDot() int32 {
	if x != nil {
		return x.RedDot
	}
	return 0
}

func (x *FloatingInfo) GetFloatingList() []*FloatingItem {
	if x != nil {
		return x.FloatingList
	}
	return nil
}

var File_unityctl_common_proto protoreflect.FileDescriptor

var file_unityctl_common_proto_rawDesc = []byte{
	0x0a, 0x15, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x63, 0x74, 0x6c, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x63, 0x74,
	0x6c, 0x1a, 0x18, 0x73, 0x6e, 0x61, 0x6b, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x58, 0x0a, 0x13, 0x53,
	0x6e, 0x61, 0x6b, 0x65, 0x43, 0x6f, 0x69, 0x6e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x49, 0x74,
	0x65, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x6d, 0x61, 0x72, 0x6b,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6d, 0x61, 0x72, 0x6b, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x66, 0x72, 0x6f, 0x6d, 0x22, 0x52, 0x0a, 0x08, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x61, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x61, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x77, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x6f, 0x77, 0x6e, 0x22, 0x2d, 0x0a, 0x09, 0x57, 0x65, 0x62,
	0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x58, 0x0a, 0x0c, 0x46, 0x6c, 0x6f, 0x61,
	0x74, 0x69, 0x6e, 0x67, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x64,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x61, 0x64, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x22, 0x9f, 0x01, 0x0a, 0x0c, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x39, 0x0a, 0x0b, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x5f, 0x6c, 0x69,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x73, 0x6e, 0x61, 0x6b, 0x65,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x49, 0x74,
	0x65, 0x6d, 0x52, 0x0a, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x17,
	0x0a, 0x07, 0x72, 0x65, 0x64, 0x5f, 0x64, 0x6f, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x72, 0x65, 0x64, 0x44, 0x6f, 0x74, 0x12, 0x3b, 0x0a, 0x0d, 0x66, 0x6c, 0x6f, 0x61, 0x74,
	0x69, 0x6e, 0x67, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x63, 0x74, 0x6c, 0x2e, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x69,
	0x6e, 0x67, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x0c, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x69, 0x6e, 0x67,
	0x4c, 0x69, 0x73, 0x74, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x2e, 0x31, 0x37, 0x7a, 0x6a,
	0x68, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x6e, 0x61, 0x6b, 0x65, 0x2f, 0x73, 0x6e, 0x61, 0x6b,
	0x65, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x63, 0x74, 0x6c,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_unityctl_common_proto_rawDescOnce sync.Once
	file_unityctl_common_proto_rawDescData = file_unityctl_common_proto_rawDesc
)

func file_unityctl_common_proto_rawDescGZIP() []byte {
	file_unityctl_common_proto_rawDescOnce.Do(func() {
		file_unityctl_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_unityctl_common_proto_rawDescData)
	})
	return file_unityctl_common_proto_rawDescData
}

var file_unityctl_common_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_unityctl_common_proto_goTypes = []interface{}{
	(*SnakeCoinDetailItem)(nil),     // 0: unityctl.SnakeCoinDetailItem
	(*TaskInfo)(nil),                // 1: unityctl.TaskInfo
	(*WebBanner)(nil),               // 2: unityctl.WebBanner
	(*FloatingItem)(nil),            // 3: unityctl.FloatingItem
	(*FloatingInfo)(nil),            // 4: unityctl.FloatingInfo
	(*snakecommon.CRewardItem)(nil), // 5: snakecommon.CRewardItem
}
var file_unityctl_common_proto_depIdxs = []int32{
	5, // 0: unityctl.FloatingInfo.reward_list:type_name -> snakecommon.CRewardItem
	3, // 1: unityctl.FloatingInfo.floating_list:type_name -> unityctl.FloatingItem
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_unityctl_common_proto_init() }
func file_unityctl_common_proto_init() {
	if File_unityctl_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_unityctl_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SnakeCoinDetailItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_unityctl_common_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_unityctl_common_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebBanner); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_unityctl_common_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FloatingItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_unityctl_common_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FloatingInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_unityctl_common_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_unityctl_common_proto_goTypes,
		DependencyIndexes: file_unityctl_common_proto_depIdxs,
		MessageInfos:      file_unityctl_common_proto_msgTypes,
	}.Build()
	File_unityctl_common_proto = out.File
	file_unityctl_common_proto_rawDesc = nil
	file_unityctl_common_proto_goTypes = nil
	file_unityctl_common_proto_depIdxs = nil
}
