// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.16.1
// source: unityctl/unityctl.proto

package unityctl

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoomState int32

const (
	RoomState_Idle      RoomState = 0 // 空闲
	RoomState_WaitEnter RoomState = 1 // 待进入
	RoomState_InGame    RoomState = 2 // 游戏中
	RoomState_WaitExit  RoomState = 3 // 待退出
	RoomState_Offline   RoomState = 4 // 离线
)

// Enum value maps for RoomState.
var (
	RoomState_name = map[int32]string{
		0: "Idle",
		1: "WaitEnter",
		2: "InGame",
		3: "WaitExit",
		4: "Offline",
	}
	RoomState_value = map[string]int32{
		"Idle":      0,
		"WaitEnter": 1,
		"InGame":    2,
		"WaitExit":  3,
		"Offline":   4,
	}
)

func (x RoomState) Enum() *RoomState {
	p := new(RoomState)
	*p = x
	return p
}

func (x RoomState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomState) Descriptor() protoreflect.EnumDescriptor {
	return file_unityctl_unityctl_proto_enumTypes[0].Descriptor()
}

func (RoomState) Type() protoreflect.EnumType {
	return &file_unityctl_unityctl_proto_enumTypes[0]
}

func (x RoomState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoomState.Descriptor instead.
func (RoomState) EnumDescriptor() ([]byte, []int) {
	return file_unityctl_unityctl_proto_rawDescGZIP(), []int{0}
}

type TeamEndlessSettleType int32

const (
	TeamEndlessSettleType_Normal   TeamEndlessSettleType = 0 // 正常主动结算
	TeamEndlessSettleType_Abnormal TeamEndlessSettleType = 1 // 异常结算
)

// Enum value maps for TeamEndlessSettleType.
var (
	TeamEndlessSettleType_name = map[int32]string{
		0: "Normal",
		1: "Abnormal",
	}
	TeamEndlessSettleType_value = map[string]int32{
		"Normal":   0,
		"Abnormal": 1,
	}
)

func (x TeamEndlessSettleType) Enum() *TeamEndlessSettleType {
	p := new(TeamEndlessSettleType)
	*p = x
	return p
}

func (x TeamEndlessSettleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TeamEndlessSettleType) Descriptor() protoreflect.EnumDescriptor {
	return file_unityctl_unityctl_proto_enumTypes[1].Descriptor()
}

func (TeamEndlessSettleType) Type() protoreflect.EnumType {
	return &file_unityctl_unityctl_proto_enumTypes[1]
}

func (x TeamEndlessSettleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TeamEndlessSettleType.Descriptor instead.
func (TeamEndlessSettleType) EnumDescriptor() ([]byte, []int) {
	return file_unityctl_unityctl_proto_rawDescGZIP(), []int{1}
}

// unity server每秒定时同步房间状态
type SyncStateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr        string    `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`                            // ip:端口
	Pid         int32     `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`                             // 进程id
	GameMode    int32     `protobuf:"varint,3,opt,name=game_mode,json=gameMode,proto3" json:"game_mode,omitempty"`   // 游戏模式
	ModeVersion int32     `protobuf:"varint,4,opt,name=modeVersion,proto3" json:"modeVersion,omitempty"`             // 模式版本号
	State       RoomState `protobuf:"varint,5,opt,name=state,proto3,enum=unityctl.RoomState" json:"state,omitempty"` // 状态
}

func (x *SyncStateReq) Reset() {
	*x = SyncStateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unityctl_unityctl_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncStateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncStateReq) ProtoMessage() {}

func (x *SyncStateReq) ProtoReflect() protoreflect.Message {
	mi := &file_unityctl_unityctl_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncStateReq.ProtoReflect.Descriptor instead.
func (*SyncStateReq) Descriptor() ([]byte, []int) {
	return file_unityctl_unityctl_proto_rawDescGZIP(), []int{0}
}

func (x *SyncStateReq) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *SyncStateReq) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *SyncStateReq) GetGameMode() int32 {
	if x != nil {
		return x.GameMode
	}
	return 0
}

func (x *SyncStateReq) GetModeVersion() int32 {
	if x != nil {
		return x.ModeVersion
	}
	return 0
}

func (x *SyncStateReq) GetState() RoomState {
	if x != nil {
		return x.State
	}
	return RoomState_Idle
}

type SyncStateRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SyncStateRsp) Reset() {
	*x = SyncStateRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unityctl_unityctl_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncStateRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncStateRsp) ProtoMessage() {}

func (x *SyncStateRsp) ProtoReflect() protoreflect.Message {
	mi := &file_unityctl_unityctl_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncStateRsp.ProtoReflect.Descriptor instead.
func (*SyncStateRsp) Descriptor() ([]byte, []int) {
	return file_unityctl_unityctl_proto_rawDescGZIP(), []int{1}
}

// 游戏开始前，unity server通知游戏开始
type StartGameReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr     string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`                          // ip:端口
	Rid      int32  `protobuf:"varint,2,opt,name=rid,proto3" json:"rid,omitempty"`                           // 房间id
	GameMode int32  `protobuf:"varint,3,opt,name=game_mode,json=gameMode,proto3" json:"game_mode,omitempty"` // 游戏模式
	Payload  []byte `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`                    // 额外数据
}

func (x *StartGameReq) Reset() {
	*x = StartGameReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unityctl_unityctl_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartGameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGameReq) ProtoMessage() {}

func (x *StartGameReq) ProtoReflect() protoreflect.Message {
	mi := &file_unityctl_unityctl_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGameReq.ProtoReflect.Descriptor instead.
func (*StartGameReq) Descriptor() ([]byte, []int) {
	return file_unityctl_unityctl_proto_rawDescGZIP(), []int{2}
}

func (x *StartGameReq) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *StartGameReq) GetRid() int32 {
	if x != nil {
		return x.Rid
	}
	return 0
}

func (x *StartGameReq) GetGameMode() int32 {
	if x != nil {
		return x.GameMode
	}
	return 0
}

func (x *StartGameReq) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type StartGameRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StartGameRsp) Reset() {
	*x = StartGameRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unityctl_unityctl_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartGameRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGameRsp) ProtoMessage() {}

func (x *StartGameRsp) ProtoReflect() protoreflect.Message {
	mi := &file_unityctl_unityctl_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGameRsp.ProtoReflect.Descriptor instead.
func (*StartGameRsp) Descriptor() ([]byte, []int) {
	return file_unityctl_unityctl_proto_rawDescGZIP(), []int{3}
}

// 游戏结束时untiy server通知游戏结果
type EndGameReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr     string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`                          // ip:端口
	Rid      int32  `protobuf:"varint,2,opt,name=rid,proto3" json:"rid,omitempty"`                           // 房间id
	GameMode int32  `protobuf:"varint,3,opt,name=game_mode,json=gameMode,proto3" json:"game_mode,omitempty"` // 游戏模式
	Payload  []byte `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`                    // 额外数据
}

func (x *EndGameReq) Reset() {
	*x = EndGameReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unityctl_unityctl_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EndGameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndGameReq) ProtoMessage() {}

func (x *EndGameReq) ProtoReflect() protoreflect.Message {
	mi := &file_unityctl_unityctl_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndGameReq.ProtoReflect.Descriptor instead.
func (*EndGameReq) Descriptor() ([]byte, []int) {
	return file_unityctl_unityctl_proto_rawDescGZIP(), []int{4}
}

func (x *EndGameReq) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *EndGameReq) GetRid() int32 {
	if x != nil {
		return x.Rid
	}
	return 0
}

func (x *EndGameReq) GetGameMode() int32 {
	if x != nil {
		return x.GameMode
	}
	return 0
}

func (x *EndGameReq) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// 玩家结算时的一些数据，同top_list_v2/update_score接口
type TeamEndlessEndGame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid              string                `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"` // 结算的玩家uid
	Platform         int32                 `protobuf:"varint,3,opt,name=platform,proto3" json:"platform,omitempty"`
	Market           string                `protobuf:"bytes,4,opt,name=market,proto3" json:"market,omitempty"`
	Version          string                `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	DeviceId         string                `protobuf:"bytes,6,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Kill             int32                 `protobuf:"varint,9,opt,name=kill,proto3" json:"kill,omitempty"`
	Length           int32                 `protobuf:"varint,10,opt,name=length,proto3" json:"length,omitempty"`
	LoginType        int32                 `protobuf:"varint,11,opt,name=login_type,json=loginType,proto3" json:"login_type,omitempty"`
	Buff             int32                 `protobuf:"varint,12,opt,name=buff,proto3" json:"buff,omitempty"`
	FirstChargeState int32                 `protobuf:"varint,13,opt,name=first_charge_state,json=firstChargeState,proto3" json:"first_charge_state,omitempty"`
	ReliveCount      int32                 `protobuf:"varint,14,opt,name=relive_count,json=reliveCount,proto3" json:"relive_count,omitempty"`
	ReliveTypes      string                `protobuf:"bytes,15,opt,name=relive_types,json=reliveTypes,proto3" json:"relive_types,omitempty"`
	SkinId           int32                 `protobuf:"varint,16,opt,name=skin_id,json=skinId,proto3" json:"skin_id,omitempty"`
	NewScore         int32                 `protobuf:"varint,17,opt,name=new_score,json=newScore,proto3" json:"new_score,omitempty"`
	GameTime         int32                 `protobuf:"varint,18,opt,name=game_time,json=gameTime,proto3" json:"game_time,omitempty"`
	DestroyLength    int32                 `protobuf:"varint,19,opt,name=destroy_length,json=destroyLength,proto3" json:"destroy_length,omitempty"`
	Score            string                `protobuf:"bytes,20,opt,name=score,proto3" json:"score,omitempty"`
	Collect          int32                 `protobuf:"varint,21,opt,name=collect,proto3" json:"collect,omitempty"`
	SettleType       TeamEndlessSettleType `protobuf:"varint,22,opt,name=settle_type,json=settleType,proto3,enum=unityctl.TeamEndlessSettleType" json:"settle_type,omitempty"` // 结算类型
}

func (x *TeamEndlessEndGame) Reset() {
	*x = TeamEndlessEndGame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unityctl_unityctl_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TeamEndlessEndGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamEndlessEndGame) ProtoMessage() {}

func (x *TeamEndlessEndGame) ProtoReflect() protoreflect.Message {
	mi := &file_unityctl_unityctl_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamEndlessEndGame.ProtoReflect.Descriptor instead.
func (*TeamEndlessEndGame) Descriptor() ([]byte, []int) {
	return file_unityctl_unityctl_proto_rawDescGZIP(), []int{5}
}

func (x *TeamEndlessEndGame) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *TeamEndlessEndGame) GetPlatform() int32 {
	if x != nil {
		return x.Platform
	}
	return 0
}

func (x *TeamEndlessEndGame) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

func (x *TeamEndlessEndGame) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *TeamEndlessEndGame) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *TeamEndlessEndGame) GetKill() int32 {
	if x != nil {
		return x.Kill
	}
	return 0
}

func (x *TeamEndlessEndGame) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *TeamEndlessEndGame) GetLoginType() int32 {
	if x != nil {
		return x.LoginType
	}
	return 0
}

func (x *TeamEndlessEndGame) GetBuff() int32 {
	if x != nil {
		return x.Buff
	}
	return 0
}

func (x *TeamEndlessEndGame) GetFirstChargeState() int32 {
	if x != nil {
		return x.FirstChargeState
	}
	return 0
}

func (x *TeamEndlessEndGame) GetReliveCount() int32 {
	if x != nil {
		return x.ReliveCount
	}
	return 0
}

func (x *TeamEndlessEndGame) GetReliveTypes() string {
	if x != nil {
		return x.ReliveTypes
	}
	return ""
}

func (x *TeamEndlessEndGame) GetSkinId() int32 {
	if x != nil {
		return x.SkinId
	}
	return 0
}

func (x *TeamEndlessEndGame) GetNewScore() int32 {
	if x != nil {
		return x.NewScore
	}
	return 0
}

func (x *TeamEndlessEndGame) GetGameTime() int32 {
	if x != nil {
		return x.GameTime
	}
	return 0
}

func (x *TeamEndlessEndGame) GetDestroyLength() int32 {
	if x != nil {
		return x.DestroyLength
	}
	return 0
}

func (x *TeamEndlessEndGame) GetScore() string {
	if x != nil {
		return x.Score
	}
	return ""
}

func (x *TeamEndlessEndGame) GetCollect() int32 {
	if x != nil {
		return x.Collect
	}
	return 0
}

func (x *TeamEndlessEndGame) GetSettleType() TeamEndlessSettleType {
	if x != nil {
		return x.SettleType
	}
	return TeamEndlessSettleType_Normal
}

type EndGameRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EndGameRsp) Reset() {
	*x = EndGameRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unityctl_unityctl_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EndGameRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndGameRsp) ProtoMessage() {}

func (x *EndGameRsp) ProtoReflect() protoreflect.Message {
	mi := &file_unityctl_unityctl_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndGameRsp.ProtoReflect.Descriptor instead.
func (*EndGameRsp) Descriptor() ([]byte, []int) {
	return file_unityctl_unityctl_proto_rawDescGZIP(), []int{6}
}

type SubscribeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"` // ip:端口
}

func (x *SubscribeReq) Reset() {
	*x = SubscribeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unityctl_unityctl_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeReq) ProtoMessage() {}

func (x *SubscribeReq) ProtoReflect() protoreflect.Message {
	mi := &file_unityctl_unityctl_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeReq.ProtoReflect.Descriptor instead.
func (*SubscribeReq) Descriptor() ([]byte, []int) {
	return file_unityctl_unityctl_proto_rawDescGZIP(), []int{7}
}

func (x *SubscribeReq) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type SubscribeRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PushType PushType `protobuf:"varint,1,opt,name=pushType,proto3,enum=unityctl.PushType" json:"pushType,omitempty"` // push 类型
	Data     []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`                                 // push内容
	MsgId    string   `protobuf:"bytes,3,opt,name=msgId,proto3" json:"msgId,omitempty"`                               // 唯一标识
}

func (x *SubscribeRsp) Reset() {
	*x = SubscribeRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unityctl_unityctl_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRsp) ProtoMessage() {}

func (x *SubscribeRsp) ProtoReflect() protoreflect.Message {
	mi := &file_unityctl_unityctl_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRsp.ProtoReflect.Descriptor instead.
func (*SubscribeRsp) Descriptor() ([]byte, []int) {
	return file_unityctl_unityctl_proto_rawDescGZIP(), []int{8}
}

func (x *SubscribeRsp) GetPushType() PushType {
	if x != nil {
		return x.PushType
	}
	return PushType_SyncGameInfo
}

func (x *SubscribeRsp) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SubscribeRsp) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

type GameReadyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ready    bool   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`          // 是否初始化成功
	MsgId    string `protobuf:"bytes,2,opt,name=msgId,proto3" json:"msgId,omitempty"`           // push消息中的唯一标识
	Addr     string `protobuf:"bytes,3,opt,name=addr,proto3" json:"addr,omitempty"`             // ip:端口
	DsId     string `protobuf:"bytes,4,opt,name=ds_id,json=dsId,proto3" json:"ds_id,omitempty"` // unity server id 标识
	Rid      int32  `protobuf:"varint,5,opt,name=rid,proto3" json:"rid,omitempty"`              // 房间 id
	GameMode int32  `protobuf:"varint,6,opt,name=game_mode,json=gameMode,proto3" json:"game_mode,omitempty"`
}

func (x *GameReadyReq) Reset() {
	*x = GameReadyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unityctl_unityctl_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameReadyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameReadyReq) ProtoMessage() {}

func (x *GameReadyReq) ProtoReflect() protoreflect.Message {
	mi := &file_unityctl_unityctl_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameReadyReq.ProtoReflect.Descriptor instead.
func (*GameReadyReq) Descriptor() ([]byte, []int) {
	return file_unityctl_unityctl_proto_rawDescGZIP(), []int{9}
}

func (x *GameReadyReq) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *GameReadyReq) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *GameReadyReq) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *GameReadyReq) GetDsId() string {
	if x != nil {
		return x.DsId
	}
	return ""
}

func (x *GameReadyReq) GetRid() int32 {
	if x != nil {
		return x.Rid
	}
	return 0
}

func (x *GameReadyReq) GetGameMode() int32 {
	if x != nil {
		return x.GameMode
	}
	return 0
}

type GameReadyRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GameReadyRsp) Reset() {
	*x = GameReadyRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unityctl_unityctl_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameReadyRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameReadyRsp) ProtoMessage() {}

func (x *GameReadyRsp) ProtoReflect() protoreflect.Message {
	mi := &file_unityctl_unityctl_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameReadyRsp.ProtoReflect.Descriptor instead.
func (*GameReadyRsp) Descriptor() ([]byte, []int) {
	return file_unityctl_unityctl_proto_rawDescGZIP(), []int{10}
}

// 上传打点
type UploadMetricReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action   string           `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Uid      string           `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Rid      int32            `protobuf:"varint,3,opt,name=rid,proto3" json:"rid,omitempty"`
	Platform int32            `protobuf:"varint,4,opt,name=platform,proto3" json:"platform,omitempty"`
	Market   string           `protobuf:"bytes,5,opt,name=market,proto3" json:"market,omitempty"`
	Version  string           `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	Kvs      *structpb.Struct `protobuf:"bytes,7,opt,name=kvs,proto3" json:"kvs,omitempty"`
}

func (x *UploadMetricReq) Reset() {
	*x = UploadMetricReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unityctl_unityctl_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadMetricReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMetricReq) ProtoMessage() {}

func (x *UploadMetricReq) ProtoReflect() protoreflect.Message {
	mi := &file_unityctl_unityctl_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMetricReq.ProtoReflect.Descriptor instead.
func (*UploadMetricReq) Descriptor() ([]byte, []int) {
	return file_unityctl_unityctl_proto_rawDescGZIP(), []int{11}
}

func (x *UploadMetricReq) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *UploadMetricReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *UploadMetricReq) GetRid() int32 {
	if x != nil {
		return x.Rid
	}
	return 0
}

func (x *UploadMetricReq) GetPlatform() int32 {
	if x != nil {
		return x.Platform
	}
	return 0
}

func (x *UploadMetricReq) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

func (x *UploadMetricReq) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *UploadMetricReq) GetKvs() *structpb.Struct {
	if x != nil {
		return x.Kvs
	}
	return nil
}

type UploadMetricRsq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UploadMetricRsq) Reset() {
	*x = UploadMetricRsq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unityctl_unityctl_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadMetricRsq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMetricRsq) ProtoMessage() {}

func (x *UploadMetricRsq) ProtoReflect() protoreflect.Message {
	mi := &file_unityctl_unityctl_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMetricRsq.ProtoReflect.Descriptor instead.
func (*UploadMetricRsq) Descriptor() ([]byte, []int) {
	return file_unityctl_unityctl_proto_rawDescGZIP(), []int{12}
}

// 获取apollo上的unity配置
type GetUnityConfigReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NamespacePrefix string   `protobuf:"bytes,1,opt,name=namespace_prefix,json=namespacePrefix,proto3" json:"namespace_prefix,omitempty"` // 命名空间前缀
	ClientVersion   string   `protobuf:"bytes,2,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`       // 客户端版本
	HotVersion      string   `protobuf:"bytes,3,opt,name=hot_version,json=hotVersion,proto3" json:"hot_version,omitempty"`                // 热更版本
	Keys            []string `protobuf:"bytes,4,rep,name=keys,proto3" json:"keys,omitempty"`
}

func (x *GetUnityConfigReq) Reset() {
	*x = GetUnityConfigReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unityctl_unityctl_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUnityConfigReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnityConfigReq) ProtoMessage() {}

func (x *GetUnityConfigReq) ProtoReflect() protoreflect.Message {
	mi := &file_unityctl_unityctl_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnityConfigReq.ProtoReflect.Descriptor instead.
func (*GetUnityConfigReq) Descriptor() ([]byte, []int) {
	return file_unityctl_unityctl_proto_rawDescGZIP(), []int{13}
}

func (x *GetUnityConfigReq) GetNamespacePrefix() string {
	if x != nil {
		return x.NamespacePrefix
	}
	return ""
}

func (x *GetUnityConfigReq) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *GetUnityConfigReq) GetHotVersion() string {
	if x != nil {
		return x.HotVersion
	}
	return ""
}

func (x *GetUnityConfigReq) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type UnityConfigItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Md5     string `protobuf:"bytes,1,opt,name=md5,proto3" json:"md5,omitempty"`
	Version int64  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Value   string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *UnityConfigItem) Reset() {
	*x = UnityConfigItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unityctl_unityctl_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnityConfigItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnityConfigItem) ProtoMessage() {}

func (x *UnityConfigItem) ProtoReflect() protoreflect.Message {
	mi := &file_unityctl_unityctl_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnityConfigItem.ProtoReflect.Descriptor instead.
func (*UnityConfigItem) Descriptor() ([]byte, []int) {
	return file_unityctl_unityctl_proto_rawDescGZIP(), []int{14}
}

func (x *UnityConfigItem) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

func (x *UnityConfigItem) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *UnityConfigItem) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type GetUnityConfigRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Configs map[string]*UnityConfigItem `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *GetUnityConfigRsp) Reset() {
	*x = GetUnityConfigRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unityctl_unityctl_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUnityConfigRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnityConfigRsp) ProtoMessage() {}

func (x *GetUnityConfigRsp) ProtoReflect() protoreflect.Message {
	mi := &file_unityctl_unityctl_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnityConfigRsp.ProtoReflect.Descriptor instead.
func (*GetUnityConfigRsp) Descriptor() ([]byte, []int) {
	return file_unityctl_unityctl_proto_rawDescGZIP(), []int{15}
}

func (x *GetUnityConfigRsp) GetConfigs() map[string]*UnityConfigItem {
	if x != nil {
		return x.Configs
	}
	return nil
}

// 获取模式版本号
type GetModeVersionReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameMode      int32  `protobuf:"varint,1,opt,name=game_mode,json=gameMode,proto3" json:"game_mode,omitempty"`
	ClientVersion string `protobuf:"bytes,2,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	HotVersion    string `protobuf:"bytes,3,opt,name=hot_version,json=hotVersion,proto3" json:"hot_version,omitempty"`
}

func (x *GetModeVersionReq) Reset() {
	*x = GetModeVersionReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unityctl_unityctl_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetModeVersionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModeVersionReq) ProtoMessage() {}

func (x *GetModeVersionReq) ProtoReflect() protoreflect.Message {
	mi := &file_unityctl_unityctl_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModeVersionReq.ProtoReflect.Descriptor instead.
func (*GetModeVersionReq) Descriptor() ([]byte, []int) {
	return file_unityctl_unityctl_proto_rawDescGZIP(), []int{16}
}

func (x *GetModeVersionReq) GetGameMode() int32 {
	if x != nil {
		return x.GameMode
	}
	return 0
}

func (x *GetModeVersionReq) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *GetModeVersionReq) GetHotVersion() string {
	if x != nil {
		return x.HotVersion
	}
	return ""
}

type GetModeVersionRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ModeVersion int32 `protobuf:"varint,1,opt,name=mode_version,json=modeVersion,proto3" json:"mode_version,omitempty"`
}

func (x *GetModeVersionRsp) Reset() {
	*x = GetModeVersionRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unityctl_unityctl_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetModeVersionRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModeVersionRsp) ProtoMessage() {}

func (x *GetModeVersionRsp) ProtoReflect() protoreflect.Message {
	mi := &file_unityctl_unityctl_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModeVersionRsp.ProtoReflect.Descriptor instead.
func (*GetModeVersionRsp) Descriptor() ([]byte, []int) {
	return file_unityctl_unityctl_proto_rawDescGZIP(), []int{17}
}

func (x *GetModeVersionRsp) GetModeVersion() int32 {
	if x != nil {
		return x.ModeVersion
	}
	return 0
}

// 获取日志上传token
type GetUploadLogTokenReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileName  string `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Directory string `protobuf:"bytes,2,opt,name=directory,proto3" json:"directory,omitempty"`
}

func (x *GetUploadLogTokenReq) Reset() {
	*x = GetUploadLogTokenReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unityctl_unityctl_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUploadLogTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUploadLogTokenReq) ProtoMessage() {}

func (x *GetUploadLogTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_unityctl_unityctl_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUploadLogTokenReq.ProtoReflect.Descriptor instead.
func (*GetUploadLogTokenReq) Descriptor() ([]byte, []int) {
	return file_unityctl_unityctl_proto_rawDescGZIP(), []int{18}
}

func (x *GetUploadLogTokenReq) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *GetUploadLogTokenReq) GetDirectory() string {
	if x != nil {
		return x.Directory
	}
	return ""
}

type GetUploadLogTokenRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Accessid  string `protobuf:"bytes,1,opt,name=accessid,proto3" json:"accessid,omitempty"`
	Host      string `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Expire    int64  `protobuf:"varint,3,opt,name=expire,proto3" json:"expire,omitempty"`
	Signature string `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	Policy    string `protobuf:"bytes,5,opt,name=policy,proto3" json:"policy,omitempty"`
	Dir       string `protobuf:"bytes,6,opt,name=dir,proto3" json:"dir,omitempty"`
	Callback  string `protobuf:"bytes,7,opt,name=callback,proto3" json:"callback,omitempty"`
	Cdnhost   string `protobuf:"bytes,8,opt,name=cdnhost,proto3" json:"cdnhost,omitempty"`
	Url       string `protobuf:"bytes,9,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *GetUploadLogTokenRsp) Reset() {
	*x = GetUploadLogTokenRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unityctl_unityctl_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUploadLogTokenRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUploadLogTokenRsp) ProtoMessage() {}

func (x *GetUploadLogTokenRsp) ProtoReflect() protoreflect.Message {
	mi := &file_unityctl_unityctl_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUploadLogTokenRsp.ProtoReflect.Descriptor instead.
func (*GetUploadLogTokenRsp) Descriptor() ([]byte, []int) {
	return file_unityctl_unityctl_proto_rawDescGZIP(), []int{19}
}

func (x *GetUploadLogTokenRsp) GetAccessid() string {
	if x != nil {
		return x.Accessid
	}
	return ""
}

func (x *GetUploadLogTokenRsp) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *GetUploadLogTokenRsp) GetExpire() int64 {
	if x != nil {
		return x.Expire
	}
	return 0
}

func (x *GetUploadLogTokenRsp) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *GetUploadLogTokenRsp) GetPolicy() string {
	if x != nil {
		return x.Policy
	}
	return ""
}

func (x *GetUploadLogTokenRsp) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

func (x *GetUploadLogTokenRsp) GetCallback() string {
	if x != nil {
		return x.Callback
	}
	return ""
}

func (x *GetUploadLogTokenRsp) GetCdnhost() string {
	if x != nil {
		return x.Cdnhost
	}
	return ""
}

func (x *GetUploadLogTokenRsp) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// 获取贪吃蛇apollo配置，版本号是最新的不下发数据
type GetSnakeConfigReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace string            `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`                                                                               // 命名空间
	Keys      map[string]string `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // 配置名 -> 版本号
}

func (x *GetSnakeConfigReq) Reset() {
	*x = GetSnakeConfigReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unityctl_unityctl_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSnakeConfigReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnakeConfigReq) ProtoMessage() {}

func (x *GetSnakeConfigReq) ProtoReflect() protoreflect.Message {
	mi := &file_unityctl_unityctl_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnakeConfigReq.ProtoReflect.Descriptor instead.
func (*GetSnakeConfigReq) Descriptor() ([]byte, []int) {
	return file_unityctl_unityctl_proto_rawDescGZIP(), []int{20}
}

func (x *GetSnakeConfigReq) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetSnakeConfigReq) GetKeys() map[string]string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type GetSnakeConfigRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Configs map[string]*SnakeConfigItem `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // 配置名 -> 配置值
}

func (x *GetSnakeConfigRsp) Reset() {
	*x = GetSnakeConfigRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unityctl_unityctl_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSnakeConfigRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnakeConfigRsp) ProtoMessage() {}

func (x *GetSnakeConfigRsp) ProtoReflect() protoreflect.Message {
	mi := &file_unityctl_unityctl_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnakeConfigRsp.ProtoReflect.Descriptor instead.
func (*GetSnakeConfigRsp) Descriptor() ([]byte, []int) {
	return file_unityctl_unityctl_proto_rawDescGZIP(), []int{21}
}

func (x *GetSnakeConfigRsp) GetConfigs() map[string]*SnakeConfigItem {
	if x != nil {
		return x.Configs
	}
	return nil
}

type SnakeConfigItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version int64  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Value   string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *SnakeConfigItem) Reset() {
	*x = SnakeConfigItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unityctl_unityctl_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SnakeConfigItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnakeConfigItem) ProtoMessage() {}

func (x *SnakeConfigItem) ProtoReflect() protoreflect.Message {
	mi := &file_unityctl_unityctl_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnakeConfigItem.ProtoReflect.Descriptor instead.
func (*SnakeConfigItem) Descriptor() ([]byte, []int) {
	return file_unityctl_unityctl_proto_rawDescGZIP(), []int{22}
}

func (x *SnakeConfigItem) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SnakeConfigItem) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_unityctl_unityctl_proto protoreflect.FileDescriptor

var file_unityctl_unityctl_proto_rawDesc = []byte{
	0x0a, 0x17, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x63, 0x74, 0x6c, 0x2f, 0x75, 0x6e, 0x69, 0x74, 0x79,
	0x63, 0x74, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x75, 0x6e, 0x69, 0x74, 0x79,
	0x63, 0x74, 0x6c, 0x1a, 0x13, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x63, 0x74, 0x6c, 0x2f, 0x70, 0x75,
	0x73, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9e, 0x01, 0x0a, 0x0c, 0x53, 0x79, 0x6e, 0x63, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x70,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x70, 0x69, 0x64, 0x12, 0x1b, 0x0a,
	0x09, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x6d, 0x6f,
	0x64, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0b, 0x6d, 0x6f, 0x64, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x29, 0x0a, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x75, 0x6e,
	0x69, 0x74, 0x79, 0x63, 0x74, 0x6c, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x0e, 0x0a, 0x0c, 0x53, 0x79, 0x6e, 0x63, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x52, 0x73, 0x70, 0x22, 0x6b, 0x0a, 0x0c, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x72,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x72, 0x69, 0x64, 0x12, 0x1b, 0x0a,
	0x09, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x22, 0x0e, 0x0a, 0x0c, 0x53, 0x74, 0x61, 0x72, 0x74, 0x47, 0x61, 0x6d,
	0x65, 0x52, 0x73, 0x70, 0x22, 0x69, 0x0a, 0x0a, 0x45, 0x6e, 0x64, 0x47, 0x61, 0x6d, 0x65, 0x52,
	0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x72, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x67, 0x61, 0x6d, 0x65,
	0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x67, 0x61, 0x6d,
	0x65, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22,
	0xd0, 0x04, 0x0a, 0x12, 0x54, 0x65, 0x61, 0x6d, 0x45, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x73, 0x45,
	0x6e, 0x64, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x74,
	0x66, 0x6f, 0x72, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x74,
	0x66, 0x6f, 0x72, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6c, 0x6c, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x6b, 0x69, 0x6c, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74,
	0x68, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12,
	0x1d, 0x0a, 0x0a, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x0b, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x09, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x62, 0x75, 0x66, 0x66, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x62, 0x75,
	0x66, 0x66, 0x12, 0x2c, 0x0a, 0x12, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x63, 0x68, 0x61, 0x72,
	0x67, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x05, 0x52, 0x10,
	0x66, 0x69, 0x72, 0x73, 0x74, 0x43, 0x68, 0x61, 0x72, 0x67, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x0e, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x72, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x6c, 0x69, 0x76,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x6b, 0x69, 0x6e, 0x5f, 0x69,
	0x64, 0x18, 0x10, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x6b, 0x69, 0x6e, 0x49, 0x64, 0x12,
	0x1b, 0x0a, 0x09, 0x6e, 0x65, 0x77, 0x5f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x11, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x6e, 0x65, 0x77, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x67, 0x61, 0x6d, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x12, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x67, 0x61, 0x6d, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x64, 0x65, 0x73,
	0x74, 0x72, 0x6f, 0x79, 0x5f, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x13, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0d, 0x64, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68,
	0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x14, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63,
	0x74, 0x18, 0x15, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74,
	0x12, 0x40, 0x0a, 0x0b, 0x73, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x16, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f, 0x2e, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x63, 0x74, 0x6c,
	0x2e, 0x54, 0x65, 0x61, 0x6d, 0x45, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x73, 0x53, 0x65, 0x74, 0x74,
	0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x73, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x22, 0x0c, 0x0a, 0x0a, 0x45, 0x6e, 0x64, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x73, 0x70,
	0x22, 0x22, 0x0a, 0x0c, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x71,
	0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x61, 0x64, 0x64, 0x72, 0x22, 0x68, 0x0a, 0x0c, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62,
	0x65, 0x52, 0x73, 0x70, 0x12, 0x2e, 0x0a, 0x08, 0x70, 0x75, 0x73, 0x68, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x63, 0x74,
	0x6c, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x70, 0x75, 0x73, 0x68,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x73, 0x67, 0x49,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x22, 0x92,
	0x01, 0x0a, 0x0c, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x61, 0x64, 0x79, 0x52, 0x65, 0x71, 0x12,
	0x14, 0x0a, 0x05, 0x72, 0x65, 0x61, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05,
	0x72, 0x65, 0x61, 0x64, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x61,
	0x64, 0x64, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x12,
	0x13, 0x0a, 0x05, 0x64, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x64, 0x73, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x72, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x6d,
	0x6f, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x4d,
	0x6f, 0x64, 0x65, 0x22, 0x0e, 0x0a, 0x0c, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x61, 0x64, 0x79,
	0x52, 0x73, 0x70, 0x22, 0xc6, 0x01, 0x0a, 0x0f, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x65,
	0x74, 0x72, 0x69, 0x63, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69,
	0x64, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x72, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12,
	0x16, 0x0a, 0x06, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x29, 0x0a, 0x03, 0x6b, 0x76, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x03, 0x6b, 0x76, 0x73, 0x22, 0x11, 0x0a, 0x0f,
	0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x52, 0x73, 0x71, 0x22,
	0x9a, 0x01, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x55, 0x6e, 0x69, 0x74, 0x79, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x52, 0x65, 0x71, 0x12, 0x29, 0x0a, 0x10, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x5f, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0f, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78,
	0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x68, 0x6f, 0x74, 0x5f, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x68, 0x6f,
	0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x22, 0x53, 0x0a, 0x0f,
	0x55, 0x6e, 0x69, 0x74, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x74, 0x65, 0x6d, 0x12,
	0x10, 0x0a, 0x03, 0x6d, 0x64, 0x35, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x64,
	0x35, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x22, 0xae, 0x01, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x55, 0x6e, 0x69, 0x74, 0x79, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x52, 0x73, 0x70, 0x12, 0x42, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x75, 0x6e, 0x69, 0x74, 0x79,
	0x63, 0x74, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x6e, 0x69, 0x74, 0x79, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x52, 0x73, 0x70, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x1a, 0x55, 0x0a, 0x0c, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2f, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x75,
	0x6e, 0x69, 0x74, 0x79, 0x63, 0x74, 0x6c, 0x2e, 0x55, 0x6e, 0x69, 0x74, 0x79, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02,
	0x38, 0x01, 0x22, 0x78, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x5f,
	0x6d, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65,
	0x4d, 0x6f, 0x64, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x68,
	0x6f, 0x74, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x68, 0x6f, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x36, 0x0a, 0x11,
	0x47, 0x65, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x73,
	0x70, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x6f, 0x64, 0x65, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x6d, 0x6f, 0x64, 0x65, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x22, 0x51, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x55, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x4c, 0x6f, 0x67, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a, 0x09,
	0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x69, 0x72,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x69,
	0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x22, 0xee, 0x01, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x55,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4c, 0x6f, 0x67, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x73, 0x70,
	0x12, 0x1a, 0x0a, 0x08, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x68, 0x6f, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x69, 0x67,
	0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x64, 0x69, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x69, 0x72,
	0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x64, 0x6e, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63,
	0x64, 0x6e, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0xa5, 0x01, 0x0a, 0x11, 0x47, 0x65, 0x74,
	0x53, 0x6e, 0x61, 0x6b, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x12, 0x1c,
	0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x39, 0x0a, 0x04,
	0x6b, 0x65, 0x79, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x75, 0x6e, 0x69,
	0x74, 0x79, 0x63, 0x74, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x6e, 0x61, 0x6b, 0x65, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x2e, 0x4b, 0x65, 0x79, 0x73, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x1a, 0x37, 0x0a, 0x09, 0x4b, 0x65, 0x79, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x22, 0xae, 0x01, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x53, 0x6e, 0x61, 0x6b, 0x65, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x52, 0x73, 0x70, 0x12, 0x42, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x63,
	0x74, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x6e, 0x61, 0x6b, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x52, 0x73, 0x70, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x1a, 0x55, 0x0a, 0x0c, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2f, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x75, 0x6e,
	0x69, 0x74, 0x79, 0x63, 0x74, 0x6c, 0x2e, 0x53, 0x6e, 0x61, 0x6b, 0x65, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38,
	0x01, 0x22, 0x41, 0x0a, 0x0f, 0x53, 0x6e, 0x61, 0x6b, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x49, 0x74, 0x65, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x2a, 0x4b, 0x0a, 0x09, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x12, 0x08, 0x0a, 0x04, 0x49, 0x64, 0x6c, 0x65, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x57,
	0x61, 0x69, 0x74, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x49, 0x6e,
	0x47, 0x61, 0x6d, 0x65, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x57, 0x61, 0x69, 0x74, 0x45, 0x78,
	0x69, 0x74, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x10,
	0x04, 0x2a, 0x31, 0x0a, 0x15, 0x54, 0x65, 0x61, 0x6d, 0x45, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x73,
	0x53, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x6f,
	0x72, 0x6d, 0x61, 0x6c, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x62, 0x6e, 0x6f, 0x72, 0x6d,
	0x61, 0x6c, 0x10, 0x01, 0x32, 0x93, 0x05, 0x0a, 0x0e, 0x55, 0x6e, 0x69, 0x74, 0x79, 0x63, 0x74,
	0x6c, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x3d, 0x0a, 0x09, 0x53, 0x79, 0x6e, 0x63, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x12, 0x16, 0x2e, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x63, 0x74, 0x6c, 0x2e,
	0x53, 0x79, 0x6e, 0x63, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x75,
	0x6e, 0x69, 0x74, 0x79, 0x63, 0x74, 0x6c, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x52, 0x73, 0x70, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x07, 0x45, 0x6e, 0x64, 0x47, 0x61, 0x6d,
	0x65, 0x12, 0x14, 0x2e, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x63, 0x74, 0x6c, 0x2e, 0x45, 0x6e, 0x64,
	0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x63,
	0x74, 0x6c, 0x2e, 0x45, 0x6e, 0x64, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x73, 0x70, 0x22, 0x00, 0x12,
	0x3d, 0x0a, 0x09, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x61, 0x64, 0x79, 0x12, 0x16, 0x2e, 0x75,
	0x6e, 0x69, 0x74, 0x79, 0x63, 0x74, 0x6c, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x61, 0x64,
	0x79, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x63, 0x74, 0x6c, 0x2e,
	0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x61, 0x64, 0x79, 0x52, 0x73, 0x70, 0x22, 0x00, 0x12, 0x3f,
	0x0a, 0x09, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x12, 0x16, 0x2e, 0x75, 0x6e,
	0x69, 0x74, 0x79, 0x63, 0x74, 0x6c, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65,
	0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x63, 0x74, 0x6c, 0x2e, 0x53,
	0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x73, 0x70, 0x22, 0x00, 0x30, 0x01, 0x12,
	0x48, 0x0a, 0x0c, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x12,
	0x19, 0x2e, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x63, 0x74, 0x6c, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x75, 0x6e, 0x69,
	0x74, 0x79, 0x63, 0x74, 0x6c, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x65, 0x74, 0x72,
	0x69, 0x63, 0x52, 0x73, 0x71, 0x22, 0x00, 0x28, 0x01, 0x12, 0x4c, 0x0a, 0x0e, 0x47, 0x65, 0x74,
	0x55, 0x6e, 0x69, 0x74, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1b, 0x2e, 0x75, 0x6e,
	0x69, 0x74, 0x79, 0x63, 0x74, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x6e, 0x69, 0x74, 0x79, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x75, 0x6e, 0x69, 0x74, 0x79,
	0x63, 0x74, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x6e, 0x69, 0x74, 0x79, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x52, 0x73, 0x70, 0x22, 0x00, 0x12, 0x4c, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4d, 0x6f,
	0x64, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x2e, 0x75, 0x6e, 0x69, 0x74,
	0x79, 0x63, 0x74, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x63, 0x74,
	0x6c, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x52, 0x73, 0x70, 0x22, 0x00, 0x12, 0x55, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x4c, 0x6f, 0x67, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1e, 0x2e, 0x75, 0x6e, 0x69,
	0x74, 0x79, 0x63, 0x74, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4c,
	0x6f, 0x67, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x1e, 0x2e, 0x75, 0x6e, 0x69,
	0x74, 0x79, 0x63, 0x74, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4c,
	0x6f, 0x67, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x73, 0x70, 0x22, 0x00, 0x12, 0x4c, 0x0a, 0x0e,
	0x47, 0x65, 0x74, 0x53, 0x6e, 0x61, 0x6b, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1b,
	0x2e, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x63, 0x74, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x6e, 0x61,
	0x6b, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x75, 0x6e,
	0x69, 0x74, 0x79, 0x63, 0x74, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x6e, 0x61, 0x6b, 0x65, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x73, 0x70, 0x22, 0x00, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69,
	0x74, 0x2e, 0x31, 0x37, 0x7a, 0x6a, 0x68, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x6e, 0x61, 0x6b,
	0x65, 0x2f, 0x73, 0x6e, 0x61, 0x6b, 0x65, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x75, 0x6e,
	0x69, 0x74, 0x79, 0x63, 0x74, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_unityctl_unityctl_proto_rawDescOnce sync.Once
	file_unityctl_unityctl_proto_rawDescData = file_unityctl_unityctl_proto_rawDesc
)

func file_unityctl_unityctl_proto_rawDescGZIP() []byte {
	file_unityctl_unityctl_proto_rawDescOnce.Do(func() {
		file_unityctl_unityctl_proto_rawDescData = protoimpl.X.CompressGZIP(file_unityctl_unityctl_proto_rawDescData)
	})
	return file_unityctl_unityctl_proto_rawDescData
}

var file_unityctl_unityctl_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_unityctl_unityctl_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_unityctl_unityctl_proto_goTypes = []interface{}{
	(RoomState)(0),               // 0: unityctl.RoomState
	(TeamEndlessSettleType)(0),   // 1: unityctl.TeamEndlessSettleType
	(*SyncStateReq)(nil),         // 2: unityctl.SyncStateReq
	(*SyncStateRsp)(nil),         // 3: unityctl.SyncStateRsp
	(*StartGameReq)(nil),         // 4: unityctl.StartGameReq
	(*StartGameRsp)(nil),         // 5: unityctl.StartGameRsp
	(*EndGameReq)(nil),           // 6: unityctl.EndGameReq
	(*TeamEndlessEndGame)(nil),   // 7: unityctl.TeamEndlessEndGame
	(*EndGameRsp)(nil),           // 8: unityctl.EndGameRsp
	(*SubscribeReq)(nil),         // 9: unityctl.SubscribeReq
	(*SubscribeRsp)(nil),         // 10: unityctl.SubscribeRsp
	(*GameReadyReq)(nil),         // 11: unityctl.GameReadyReq
	(*GameReadyRsp)(nil),         // 12: unityctl.GameReadyRsp
	(*UploadMetricReq)(nil),      // 13: unityctl.UploadMetricReq
	(*UploadMetricRsq)(nil),      // 14: unityctl.UploadMetricRsq
	(*GetUnityConfigReq)(nil),    // 15: unityctl.GetUnityConfigReq
	(*UnityConfigItem)(nil),      // 16: unityctl.UnityConfigItem
	(*GetUnityConfigRsp)(nil),    // 17: unityctl.GetUnityConfigRsp
	(*GetModeVersionReq)(nil),    // 18: unityctl.GetModeVersionReq
	(*GetModeVersionRsp)(nil),    // 19: unityctl.GetModeVersionRsp
	(*GetUploadLogTokenReq)(nil), // 20: unityctl.GetUploadLogTokenReq
	(*GetUploadLogTokenRsp)(nil), // 21: unityctl.GetUploadLogTokenRsp
	(*GetSnakeConfigReq)(nil),    // 22: unityctl.GetSnakeConfigReq
	(*GetSnakeConfigRsp)(nil),    // 23: unityctl.GetSnakeConfigRsp
	(*SnakeConfigItem)(nil),      // 24: unityctl.SnakeConfigItem
	nil,                          // 25: unityctl.GetUnityConfigRsp.ConfigsEntry
	nil,                          // 26: unityctl.GetSnakeConfigReq.KeysEntry
	nil,                          // 27: unityctl.GetSnakeConfigRsp.ConfigsEntry
	(PushType)(0),                // 28: unityctl.PushType
	(*structpb.Struct)(nil),      // 29: google.protobuf.Struct
}
var file_unityctl_unityctl_proto_depIdxs = []int32{
	0,  // 0: unityctl.SyncStateReq.state:type_name -> unityctl.RoomState
	1,  // 1: unityctl.TeamEndlessEndGame.settle_type:type_name -> unityctl.TeamEndlessSettleType
	28, // 2: unityctl.SubscribeRsp.pushType:type_name -> unityctl.PushType
	29, // 3: unityctl.UploadMetricReq.kvs:type_name -> google.protobuf.Struct
	25, // 4: unityctl.GetUnityConfigRsp.configs:type_name -> unityctl.GetUnityConfigRsp.ConfigsEntry
	26, // 5: unityctl.GetSnakeConfigReq.keys:type_name -> unityctl.GetSnakeConfigReq.KeysEntry
	27, // 6: unityctl.GetSnakeConfigRsp.configs:type_name -> unityctl.GetSnakeConfigRsp.ConfigsEntry
	16, // 7: unityctl.GetUnityConfigRsp.ConfigsEntry.value:type_name -> unityctl.UnityConfigItem
	24, // 8: unityctl.GetSnakeConfigRsp.ConfigsEntry.value:type_name -> unityctl.SnakeConfigItem
	2,  // 9: unityctl.UnityctlServer.SyncState:input_type -> unityctl.SyncStateReq
	6,  // 10: unityctl.UnityctlServer.EndGame:input_type -> unityctl.EndGameReq
	11, // 11: unityctl.UnityctlServer.GameReady:input_type -> unityctl.GameReadyReq
	9,  // 12: unityctl.UnityctlServer.Subscribe:input_type -> unityctl.SubscribeReq
	13, // 13: unityctl.UnityctlServer.UploadMetric:input_type -> unityctl.UploadMetricReq
	15, // 14: unityctl.UnityctlServer.GetUnityConfig:input_type -> unityctl.GetUnityConfigReq
	18, // 15: unityctl.UnityctlServer.GetModeVersion:input_type -> unityctl.GetModeVersionReq
	20, // 16: unityctl.UnityctlServer.GetUploadLogToken:input_type -> unityctl.GetUploadLogTokenReq
	22, // 17: unityctl.UnityctlServer.GetSnakeConfig:input_type -> unityctl.GetSnakeConfigReq
	3,  // 18: unityctl.UnityctlServer.SyncState:output_type -> unityctl.SyncStateRsp
	8,  // 19: unityctl.UnityctlServer.EndGame:output_type -> unityctl.EndGameRsp
	12, // 20: unityctl.UnityctlServer.GameReady:output_type -> unityctl.GameReadyRsp
	10, // 21: unityctl.UnityctlServer.Subscribe:output_type -> unityctl.SubscribeRsp
	14, // 22: unityctl.UnityctlServer.UploadMetric:output_type -> unityctl.UploadMetricRsq
	17, // 23: unityctl.UnityctlServer.GetUnityConfig:output_type -> unityctl.GetUnityConfigRsp
	19, // 24: unityctl.UnityctlServer.GetModeVersion:output_type -> unityctl.GetModeVersionRsp
	21, // 25: unityctl.UnityctlServer.GetUploadLogToken:output_type -> unityctl.GetUploadLogTokenRsp
	23, // 26: unityctl.UnityctlServer.GetSnakeConfig:output_type -> unityctl.GetSnakeConfigRsp
	18, // [18:27] is the sub-list for method output_type
	9,  // [9:18] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_unityctl_unityctl_proto_init() }
func file_unityctl_unityctl_proto_init() {
	if File_unityctl_unityctl_proto != nil {
		return
	}
	file_unityctl_push_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_unityctl_unityctl_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncStateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_unityctl_unityctl_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncStateRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_unityctl_unityctl_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartGameReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_unityctl_unityctl_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartGameRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_unityctl_unityctl_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EndGameReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_unityctl_unityctl_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TeamEndlessEndGame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_unityctl_unityctl_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EndGameRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_unityctl_unityctl_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscribeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_unityctl_unityctl_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscribeRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_unityctl_unityctl_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameReadyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_unityctl_unityctl_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameReadyRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_unityctl_unityctl_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadMetricReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_unityctl_unityctl_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadMetricRsq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_unityctl_unityctl_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUnityConfigReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_unityctl_unityctl_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnityConfigItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_unityctl_unityctl_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUnityConfigRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_unityctl_unityctl_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetModeVersionReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_unityctl_unityctl_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetModeVersionRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_unityctl_unityctl_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUploadLogTokenReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_unityctl_unityctl_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUploadLogTokenRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_unityctl_unityctl_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSnakeConfigReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_unityctl_unityctl_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSnakeConfigRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_unityctl_unityctl_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SnakeConfigItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_unityctl_unityctl_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_unityctl_unityctl_proto_goTypes,
		DependencyIndexes: file_unityctl_unityctl_proto_depIdxs,
		EnumInfos:         file_unityctl_unityctl_proto_enumTypes,
		MessageInfos:      file_unityctl_unityctl_proto_msgTypes,
	}.Build()
	File_unityctl_unityctl_proto = out.File
	file_unityctl_unityctl_proto_rawDesc = nil
	file_unityctl_unityctl_proto_goTypes = nil
	file_unityctl_unityctl_proto_depIdxs = nil
}
