variables:
  GIT_DEPTH: 1
  CI_JOB_TOKEN: fVMS_Tt6soxv4qfJtLni

stages:
  - build

build:
  image: golang:1.17.5-stretch
  stage: build
  script:
    - export GOPROXY="https://goproxy.cn,direct"
    - go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.27.1
    - go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1.0
    - wget https://github.91chi.fun/https://github.com//protocolbuffers/protobuf/releases/download/v3.16.1/protoc-3.16.1-linux-x86_64.zip
    - sed -i -E 's/(deb|security).debian.org/mirrors.aliyun.com/g' /etc/apt/sources.list
    - apt-get update -y && apt install unzip -y
    - unzip -o protoc-3.16.1-linux-x86_64.zip -d /usr/local bin/protoc
    - rm -rf protoc-3.16.1-linux-x86_64*
    - echo 'export PATH="$PATH:$(go env GOPATH)/bin"' >> $HOME/.bashrc
    - source $HOME/.bashrc
    - protoc --version
    - make
    - git config --global user.email "gitlab@example.com"
    - git config --global user.name "gitlab ci"
    - git add .
    - "git commit -m 'feat: protobuf [ci skip]'"
    - git remote set-url  origin https://gitlab-ci-token:${CI_JOB_TOKEN}@git.17zjh.com/snake/snake_proto.git
    - git push origin HEAD:master
  only:
    - master
