variables:
  GIT_DEPTH: 1
  CI_JOB_TOKEN: fVMS_Tt6soxv4qfJtLni

stages:
  - build

build:
  image: public-acr-sh-aliyun-registry.cn-shanghai.cr.aliyuncs.com/tools/golang:1.20.14-bullseye
  stage: build
  script:
    - export GOPROXY="https://goproxy.cn,direct"
    - go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.27.1
    - go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1.0
    - wget https://wepie-sre.oss-cn-shanghai.aliyuncs.com/protoc-3.16.1-linux-x86_64
    - mv protoc-3.16.1-linux-x86_64 /usr/local/bin/protoc
    - chmod +x /usr/local/bin/protoc
    - echo 'export PATH="$PATH:$(go env GOPATH)/bin"' >> $HOME/.bashrc
    - source $HOME/.bashrc
    - protoc --version
    - make
    - git config --global user.email "gitlab@example.com"
    - git config --global user.name "gitlab ci"
    - git add .
    - "git commit -m 'feat: protobuf [ci skip]'"
    - git remote set-url  origin https://gitlab-ci-token:${CI_JOB_TOKEN}@git.17zjh.com/snake/snake_proto.git
    - git push origin HEAD:master
  only:
    - master
