// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.16.1
// source: matchx/match/dream_game.proto

package match

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DreamGameGroupMember struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DreamGameGroupMember) Reset() {
	*x = DreamGameGroupMember{}
	if protoimpl.UnsafeEnabled {
		mi := &file_matchx_match_dream_game_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DreamGameGroupMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DreamGameGroupMember) ProtoMessage() {}

func (x *DreamGameGroupMember) ProtoReflect() protoreflect.Message {
	mi := &file_matchx_match_dream_game_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DreamGameGroupMember.ProtoReflect.Descriptor instead.
func (*DreamGameGroupMember) Descriptor() ([]byte, []int) {
	return file_matchx_match_dream_game_proto_rawDescGZIP(), []int{0}
}

type DreamGameSyncGroupMemberNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DreamGameSyncGroupMemberNotify) Reset() {
	*x = DreamGameSyncGroupMemberNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_matchx_match_dream_game_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DreamGameSyncGroupMemberNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DreamGameSyncGroupMemberNotify) ProtoMessage() {}

func (x *DreamGameSyncGroupMemberNotify) ProtoReflect() protoreflect.Message {
	mi := &file_matchx_match_dream_game_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DreamGameSyncGroupMemberNotify.ProtoReflect.Descriptor instead.
func (*DreamGameSyncGroupMemberNotify) Descriptor() ([]byte, []int) {
	return file_matchx_match_dream_game_proto_rawDescGZIP(), []int{1}
}

type DreamGameMatchSuccess struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"` // unityserver房间ip地址和端口信息
}

func (x *DreamGameMatchSuccess) Reset() {
	*x = DreamGameMatchSuccess{}
	if protoimpl.UnsafeEnabled {
		mi := &file_matchx_match_dream_game_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DreamGameMatchSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DreamGameMatchSuccess) ProtoMessage() {}

func (x *DreamGameMatchSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_matchx_match_dream_game_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DreamGameMatchSuccess.ProtoReflect.Descriptor instead.
func (*DreamGameMatchSuccess) Descriptor() ([]byte, []int) {
	return file_matchx_match_dream_game_proto_rawDescGZIP(), []int{2}
}

func (x *DreamGameMatchSuccess) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

type DreamGameUploadAttr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Props []*DreamGameProps `protobuf:"bytes,1,rep,name=props,proto3" json:"props,omitempty"` // 道具列表
	Coin  int64             `protobuf:"varint,2,opt,name=coin,proto3" json:"coin,omitempty"`  // 金币
}

func (x *DreamGameUploadAttr) Reset() {
	*x = DreamGameUploadAttr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_matchx_match_dream_game_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DreamGameUploadAttr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DreamGameUploadAttr) ProtoMessage() {}

func (x *DreamGameUploadAttr) ProtoReflect() protoreflect.Message {
	mi := &file_matchx_match_dream_game_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DreamGameUploadAttr.ProtoReflect.Descriptor instead.
func (*DreamGameUploadAttr) Descriptor() ([]byte, []int) {
	return file_matchx_match_dream_game_proto_rawDescGZIP(), []int{3}
}

func (x *DreamGameUploadAttr) GetProps() []*DreamGameProps {
	if x != nil {
		return x.Props
	}
	return nil
}

func (x *DreamGameUploadAttr) GetCoin() int64 {
	if x != nil {
		return x.Coin
	}
	return 0
}

type DreamGameProps struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemId     int64 `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"` // 物品ID
	Count      int64 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`                 // 数量
	Durability int64 `protobuf:"varint,3,opt,name=durability,proto3" json:"durability,omitempty"`       // 持久度
}

func (x *DreamGameProps) Reset() {
	*x = DreamGameProps{}
	if protoimpl.UnsafeEnabled {
		mi := &file_matchx_match_dream_game_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DreamGameProps) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DreamGameProps) ProtoMessage() {}

func (x *DreamGameProps) ProtoReflect() protoreflect.Message {
	mi := &file_matchx_match_dream_game_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DreamGameProps.ProtoReflect.Descriptor instead.
func (*DreamGameProps) Descriptor() ([]byte, []int) {
	return file_matchx_match_dream_game_proto_rawDescGZIP(), []int{4}
}

func (x *DreamGameProps) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *DreamGameProps) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *DreamGameProps) GetDurability() int64 {
	if x != nil {
		return x.Durability
	}
	return 0
}

type DreamGameRoomMember struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Props []*DreamGameProps `protobuf:"bytes,1,rep,name=props,proto3" json:"props,omitempty"` // 道具列表
	Coin  int64             `protobuf:"varint,2,opt,name=coin,proto3" json:"coin,omitempty"`  // 金币
}

func (x *DreamGameRoomMember) Reset() {
	*x = DreamGameRoomMember{}
	if protoimpl.UnsafeEnabled {
		mi := &file_matchx_match_dream_game_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DreamGameRoomMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DreamGameRoomMember) ProtoMessage() {}

func (x *DreamGameRoomMember) ProtoReflect() protoreflect.Message {
	mi := &file_matchx_match_dream_game_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DreamGameRoomMember.ProtoReflect.Descriptor instead.
func (*DreamGameRoomMember) Descriptor() ([]byte, []int) {
	return file_matchx_match_dream_game_proto_rawDescGZIP(), []int{5}
}

func (x *DreamGameRoomMember) GetProps() []*DreamGameProps {
	if x != nil {
		return x.Props
	}
	return nil
}

func (x *DreamGameRoomMember) GetCoin() int64 {
	if x != nil {
		return x.Coin
	}
	return 0
}

var File_matchx_match_dream_game_proto protoreflect.FileDescriptor

var file_matchx_match_dream_game_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x78, 0x2f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x2f, 0x64,
	0x72, 0x65, 0x61, 0x6d, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x22, 0x16, 0x0a, 0x14, 0x44, 0x72, 0x65, 0x61, 0x6d, 0x47,
	0x61, 0x6d, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x20,
	0x0a, 0x1e, 0x44, 0x72, 0x65, 0x61, 0x6d, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x79, 0x6e, 0x63, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79,
	0x22, 0x2b, 0x0a, 0x15, 0x44, 0x72, 0x65, 0x61, 0x6d, 0x47, 0x61, 0x6d, 0x65, 0x4d, 0x61, 0x74,
	0x63, 0x68, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x22, 0x56, 0x0a,
	0x13, 0x44, 0x72, 0x65, 0x61, 0x6d, 0x47, 0x61, 0x6d, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x41, 0x74, 0x74, 0x72, 0x12, 0x2b, 0x0a, 0x05, 0x70, 0x72, 0x6f, 0x70, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x2e, 0x44, 0x72, 0x65, 0x61,
	0x6d, 0x47, 0x61, 0x6d, 0x65, 0x50, 0x72, 0x6f, 0x70, 0x73, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x70,
	0x73, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x63, 0x6f, 0x69, 0x6e, 0x22, 0x5f, 0x0a, 0x0e, 0x44, 0x72, 0x65, 0x61, 0x6d, 0x47, 0x61,
	0x6d, 0x65, 0x50, 0x72, 0x6f, 0x70, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x75, 0x72, 0x61, 0x62, 0x69,
	0x6c, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x64, 0x75, 0x72, 0x61,
	0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x22, 0x56, 0x0a, 0x13, 0x44, 0x72, 0x65, 0x61, 0x6d, 0x47,
	0x61, 0x6d, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x2b, 0x0a,
	0x05, 0x70, 0x72, 0x6f, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d,
	0x61, 0x74, 0x63, 0x68, 0x2e, 0x44, 0x72, 0x65, 0x61, 0x6d, 0x47, 0x61, 0x6d, 0x65, 0x50, 0x72,
	0x6f, 0x70, 0x73, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x70, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x69, 0x6e, 0x42, 0x2e,
	0x5a, 0x2c, 0x67, 0x69, 0x74, 0x2e, 0x31, 0x37, 0x7a, 0x6a, 0x68, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x73, 0x6e, 0x61, 0x6b, 0x65, 0x2f, 0x73, 0x6e, 0x61, 0x6b, 0x65, 0x5f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x78, 0x2f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_matchx_match_dream_game_proto_rawDescOnce sync.Once
	file_matchx_match_dream_game_proto_rawDescData = file_matchx_match_dream_game_proto_rawDesc
)

func file_matchx_match_dream_game_proto_rawDescGZIP() []byte {
	file_matchx_match_dream_game_proto_rawDescOnce.Do(func() {
		file_matchx_match_dream_game_proto_rawDescData = protoimpl.X.CompressGZIP(file_matchx_match_dream_game_proto_rawDescData)
	})
	return file_matchx_match_dream_game_proto_rawDescData
}

var file_matchx_match_dream_game_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_matchx_match_dream_game_proto_goTypes = []interface{}{
	(*DreamGameGroupMember)(nil),           // 0: match.DreamGameGroupMember
	(*DreamGameSyncGroupMemberNotify)(nil), // 1: match.DreamGameSyncGroupMemberNotify
	(*DreamGameMatchSuccess)(nil),          // 2: match.DreamGameMatchSuccess
	(*DreamGameUploadAttr)(nil),            // 3: match.DreamGameUploadAttr
	(*DreamGameProps)(nil),                 // 4: match.DreamGameProps
	(*DreamGameRoomMember)(nil),            // 5: match.DreamGameRoomMember
}
var file_matchx_match_dream_game_proto_depIdxs = []int32{
	4, // 0: match.DreamGameUploadAttr.props:type_name -> match.DreamGameProps
	4, // 1: match.DreamGameRoomMember.props:type_name -> match.DreamGameProps
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_matchx_match_dream_game_proto_init() }
func file_matchx_match_dream_game_proto_init() {
	if File_matchx_match_dream_game_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_matchx_match_dream_game_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DreamGameGroupMember); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_matchx_match_dream_game_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DreamGameSyncGroupMemberNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_matchx_match_dream_game_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DreamGameMatchSuccess); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_matchx_match_dream_game_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DreamGameUploadAttr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_matchx_match_dream_game_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DreamGameProps); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_matchx_match_dream_game_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DreamGameRoomMember); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_matchx_match_dream_game_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_matchx_match_dream_game_proto_goTypes,
		DependencyIndexes: file_matchx_match_dream_game_proto_depIdxs,
		MessageInfos:      file_matchx_match_dream_game_proto_msgTypes,
	}.Build()
	File_matchx_match_dream_game_proto = out.File
	file_matchx_match_dream_game_proto_rawDesc = nil
	file_matchx_match_dream_game_proto_goTypes = nil
	file_matchx_match_dream_game_proto_depIdxs = nil
}
