// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.16.1
// source: matchx/match/team_endless.proto

package match

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TeamEndlessGroupMember struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TeamEndlessGroupMember) Reset() {
	*x = TeamEndlessGroupMember{}
	if protoimpl.UnsafeEnabled {
		mi := &file_matchx_match_team_endless_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TeamEndlessGroupMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamEndlessGroupMember) ProtoMessage() {}

func (x *TeamEndlessGroupMember) ProtoReflect() protoreflect.Message {
	mi := &file_matchx_match_team_endless_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamEndlessGroupMember.ProtoReflect.Descriptor instead.
func (*TeamEndlessGroupMember) Descriptor() ([]byte, []int) {
	return file_matchx_match_team_endless_proto_rawDescGZIP(), []int{0}
}

type TeamEndlessSyncGroupMemberNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MaxStar int64 `protobuf:"varint,1,opt,name=max_star,json=maxStar,proto3" json:"max_star,omitempty"` // 组队中的最大历史最大星星数 (HistoryMaxStar)
	Boss    int32 `protobuf:"varint,2,opt,name=boss,proto3" json:"boss,omitempty"`                      // 是否开启boss功能，0: 未开启 1: 开启
}

func (x *TeamEndlessSyncGroupMemberNotify) Reset() {
	*x = TeamEndlessSyncGroupMemberNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_matchx_match_team_endless_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TeamEndlessSyncGroupMemberNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamEndlessSyncGroupMemberNotify) ProtoMessage() {}

func (x *TeamEndlessSyncGroupMemberNotify) ProtoReflect() protoreflect.Message {
	mi := &file_matchx_match_team_endless_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamEndlessSyncGroupMemberNotify.ProtoReflect.Descriptor instead.
func (*TeamEndlessSyncGroupMemberNotify) Descriptor() ([]byte, []int) {
	return file_matchx_match_team_endless_proto_rawDescGZIP(), []int{1}
}

func (x *TeamEndlessSyncGroupMemberNotify) GetMaxStar() int64 {
	if x != nil {
		return x.MaxStar
	}
	return 0
}

func (x *TeamEndlessSyncGroupMemberNotify) GetBoss() int32 {
	if x != nil {
		return x.Boss
	}
	return 0
}

type TeamEndlessMatchSuccess struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`  // unityserver房间ip地址和端口信息
	Boss int32  `protobuf:"varint,2,opt,name=boss,proto3" json:"boss,omitempty"` // 是否开启boss功能，0: 未开启 1: 开启
}

func (x *TeamEndlessMatchSuccess) Reset() {
	*x = TeamEndlessMatchSuccess{}
	if protoimpl.UnsafeEnabled {
		mi := &file_matchx_match_team_endless_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TeamEndlessMatchSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamEndlessMatchSuccess) ProtoMessage() {}

func (x *TeamEndlessMatchSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_matchx_match_team_endless_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamEndlessMatchSuccess.ProtoReflect.Descriptor instead.
func (*TeamEndlessMatchSuccess) Descriptor() ([]byte, []int) {
	return file_matchx_match_team_endless_proto_rawDescGZIP(), []int{2}
}

func (x *TeamEndlessMatchSuccess) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *TeamEndlessMatchSuccess) GetBoss() int32 {
	if x != nil {
		return x.Boss
	}
	return 0
}

type TeamEndlessUploadAttr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TeamEndlessUploadAttr) Reset() {
	*x = TeamEndlessUploadAttr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_matchx_match_team_endless_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TeamEndlessUploadAttr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamEndlessUploadAttr) ProtoMessage() {}

func (x *TeamEndlessUploadAttr) ProtoReflect() protoreflect.Message {
	mi := &file_matchx_match_team_endless_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamEndlessUploadAttr.ProtoReflect.Descriptor instead.
func (*TeamEndlessUploadAttr) Descriptor() ([]byte, []int) {
	return file_matchx_match_team_endless_proto_rawDescGZIP(), []int{3}
}

type TeamEndlessRoomMember struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameCount int64 `protobuf:"varint,1,opt,name=game_count,json=gameCount,proto3" json:"game_count,omitempty"` // 游戏局数
}

func (x *TeamEndlessRoomMember) Reset() {
	*x = TeamEndlessRoomMember{}
	if protoimpl.UnsafeEnabled {
		mi := &file_matchx_match_team_endless_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TeamEndlessRoomMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamEndlessRoomMember) ProtoMessage() {}

func (x *TeamEndlessRoomMember) ProtoReflect() protoreflect.Message {
	mi := &file_matchx_match_team_endless_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamEndlessRoomMember.ProtoReflect.Descriptor instead.
func (*TeamEndlessRoomMember) Descriptor() ([]byte, []int) {
	return file_matchx_match_team_endless_proto_rawDescGZIP(), []int{4}
}

func (x *TeamEndlessRoomMember) GetGameCount() int64 {
	if x != nil {
		return x.GameCount
	}
	return 0
}

var File_matchx_match_team_endless_proto protoreflect.FileDescriptor

var file_matchx_match_team_endless_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x78, 0x2f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x2f, 0x74,
	0x65, 0x61, 0x6d, 0x5f, 0x65, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x22, 0x18, 0x0a, 0x16, 0x54, 0x65, 0x61, 0x6d,
	0x45, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x73, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x22, 0x51, 0x0a, 0x20, 0x54, 0x65, 0x61, 0x6d, 0x45, 0x6e, 0x64, 0x6c, 0x65, 0x73,
	0x73, 0x53, 0x79, 0x6e, 0x63, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x61, 0x78, 0x5f, 0x73, 0x74,
	0x61, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6d, 0x61, 0x78, 0x53, 0x74, 0x61,
	0x72, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x62, 0x6f, 0x73, 0x73, 0x22, 0x41, 0x0a, 0x17, 0x54, 0x65, 0x61, 0x6d, 0x45, 0x6e, 0x64,
	0x6c, 0x65, 0x73, 0x73, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x68, 0x6f, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x62, 0x6f, 0x73, 0x73, 0x22, 0x17, 0x0a, 0x15, 0x54, 0x65, 0x61, 0x6d,
	0x45, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x73, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x41, 0x74, 0x74,
	0x72, 0x22, 0x36, 0x0a, 0x15, 0x54, 0x65, 0x61, 0x6d, 0x45, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x73,
	0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x67, 0x61,
	0x6d, 0x65, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x67, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74,
	0x2e, 0x31, 0x37, 0x7a, 0x6a, 0x68, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x6e, 0x61, 0x6b, 0x65,
	0x2f, 0x73, 0x6e, 0x61, 0x6b, 0x65, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x61, 0x74,
	0x63, 0x68, 0x78, 0x2f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_matchx_match_team_endless_proto_rawDescOnce sync.Once
	file_matchx_match_team_endless_proto_rawDescData = file_matchx_match_team_endless_proto_rawDesc
)

func file_matchx_match_team_endless_proto_rawDescGZIP() []byte {
	file_matchx_match_team_endless_proto_rawDescOnce.Do(func() {
		file_matchx_match_team_endless_proto_rawDescData = protoimpl.X.CompressGZIP(file_matchx_match_team_endless_proto_rawDescData)
	})
	return file_matchx_match_team_endless_proto_rawDescData
}

var file_matchx_match_team_endless_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_matchx_match_team_endless_proto_goTypes = []interface{}{
	(*TeamEndlessGroupMember)(nil),           // 0: match.TeamEndlessGroupMember
	(*TeamEndlessSyncGroupMemberNotify)(nil), // 1: match.TeamEndlessSyncGroupMemberNotify
	(*TeamEndlessMatchSuccess)(nil),          // 2: match.TeamEndlessMatchSuccess
	(*TeamEndlessUploadAttr)(nil),            // 3: match.TeamEndlessUploadAttr
	(*TeamEndlessRoomMember)(nil),            // 4: match.TeamEndlessRoomMember
}
var file_matchx_match_team_endless_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_matchx_match_team_endless_proto_init() }
func file_matchx_match_team_endless_proto_init() {
	if File_matchx_match_team_endless_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_matchx_match_team_endless_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TeamEndlessGroupMember); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_matchx_match_team_endless_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TeamEndlessSyncGroupMemberNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_matchx_match_team_endless_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TeamEndlessMatchSuccess); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_matchx_match_team_endless_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TeamEndlessUploadAttr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_matchx_match_team_endless_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TeamEndlessRoomMember); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_matchx_match_team_endless_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_matchx_match_team_endless_proto_goTypes,
		DependencyIndexes: file_matchx_match_team_endless_proto_depIdxs,
		MessageInfos:      file_matchx_match_team_endless_proto_msgTypes,
	}.Build()
	File_matchx_match_team_endless_proto = out.File
	file_matchx_match_team_endless_proto_rawDesc = nil
	file_matchx_match_team_endless_proto_goTypes = nil
	file_matchx_match_team_endless_proto_depIdxs = nil
}
