// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.16.1
// source: matchx/match/unity_qualify.proto

package match

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UnityQualifyUploadAttr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SkinIdList      []int64      `protobuf:"varint,1,rep,packed,name=skin_id_list,json=skinIdList,proto3" json:"skin_id_list,omitempty"`
	SuitId          int64        `protobuf:"varint,2,opt,name=suit_id,json=suitId,proto3" json:"suit_id,omitempty"`
	TeamBroadcastId int64        `protobuf:"varint,3,opt,name=team_broadcast_id,json=teamBroadcastId,proto3" json:"team_broadcast_id,omitempty"`
	TeamBubbleId    int64        `protobuf:"varint,4,opt,name=team_bubble_id,json=teamBubbleId,proto3" json:"team_bubble_id,omitempty"`
	SkinSkillList   []*SkinSkill `protobuf:"bytes,5,rep,name=skin_skill_list,json=skinSkillList,proto3" json:"skin_skill_list,omitempty"`
}

func (x *UnityQualifyUploadAttr) Reset() {
	*x = UnityQualifyUploadAttr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_matchx_match_unity_qualify_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnityQualifyUploadAttr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnityQualifyUploadAttr) ProtoMessage() {}

func (x *UnityQualifyUploadAttr) ProtoReflect() protoreflect.Message {
	mi := &file_matchx_match_unity_qualify_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnityQualifyUploadAttr.ProtoReflect.Descriptor instead.
func (*UnityQualifyUploadAttr) Descriptor() ([]byte, []int) {
	return file_matchx_match_unity_qualify_proto_rawDescGZIP(), []int{0}
}

func (x *UnityQualifyUploadAttr) GetSkinIdList() []int64 {
	if x != nil {
		return x.SkinIdList
	}
	return nil
}

func (x *UnityQualifyUploadAttr) GetSuitId() int64 {
	if x != nil {
		return x.SuitId
	}
	return 0
}

func (x *UnityQualifyUploadAttr) GetTeamBroadcastId() int64 {
	if x != nil {
		return x.TeamBroadcastId
	}
	return 0
}

func (x *UnityQualifyUploadAttr) GetTeamBubbleId() int64 {
	if x != nil {
		return x.TeamBubbleId
	}
	return 0
}

func (x *UnityQualifyUploadAttr) GetSkinSkillList() []*SkinSkill {
	if x != nil {
		return x.SkinSkillList
	}
	return nil
}

type ReportRoomScoreNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReportRoomScoreNotify) Reset() {
	*x = ReportRoomScoreNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_matchx_match_unity_qualify_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportRoomScoreNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportRoomScoreNotify) ProtoMessage() {}

func (x *ReportRoomScoreNotify) ProtoReflect() protoreflect.Message {
	mi := &file_matchx_match_unity_qualify_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportRoomScoreNotify.ProtoReflect.Descriptor instead.
func (*ReportRoomScoreNotify) Descriptor() ([]byte, []int) {
	return file_matchx_match_unity_qualify_proto_rawDescGZIP(), []int{1}
}

type SkinSkill struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SkillType int32   `protobuf:"varint,1,opt,name=skill_type,json=skillType,proto3" json:"skill_type,omitempty"`
	Value     float64 `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *SkinSkill) Reset() {
	*x = SkinSkill{}
	if protoimpl.UnsafeEnabled {
		mi := &file_matchx_match_unity_qualify_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SkinSkill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkinSkill) ProtoMessage() {}

func (x *SkinSkill) ProtoReflect() protoreflect.Message {
	mi := &file_matchx_match_unity_qualify_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkinSkill.ProtoReflect.Descriptor instead.
func (*SkinSkill) Descriptor() ([]byte, []int) {
	return file_matchx_match_unity_qualify_proto_rawDescGZIP(), []int{2}
}

func (x *SkinSkill) GetSkillType() int32 {
	if x != nil {
		return x.SkillType
	}
	return 0
}

func (x *SkinSkill) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type UnityQualifyRoomMember struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AiLevel         int32   `protobuf:"varint,1,opt,name=ai_level,json=aiLevel,proto3" json:"ai_level,omitempty"`
	TeamBroadcastId int64   `protobuf:"varint,2,opt,name=team_broadcast_id,json=teamBroadcastId,proto3" json:"team_broadcast_id,omitempty"`
	TeamBubbleId    int64   `protobuf:"varint,3,opt,name=team_bubble_id,json=teamBubbleId,proto3" json:"team_bubble_id,omitempty"`
	SuitId          int64   `protobuf:"varint,4,opt,name=suit_id,json=suitId,proto3" json:"suit_id,omitempty"`
	SuitChosen      int32   `protobuf:"varint,5,opt,name=suit_chosen,json=suitChosen,proto3" json:"suit_chosen,omitempty"`
	SkinIdList      []int64 `protobuf:"varint,6,rep,packed,name=skin_id_list,json=skinIdList,proto3" json:"skin_id_list,omitempty"`
}

func (x *UnityQualifyRoomMember) Reset() {
	*x = UnityQualifyRoomMember{}
	if protoimpl.UnsafeEnabled {
		mi := &file_matchx_match_unity_qualify_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnityQualifyRoomMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnityQualifyRoomMember) ProtoMessage() {}

func (x *UnityQualifyRoomMember) ProtoReflect() protoreflect.Message {
	mi := &file_matchx_match_unity_qualify_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnityQualifyRoomMember.ProtoReflect.Descriptor instead.
func (*UnityQualifyRoomMember) Descriptor() ([]byte, []int) {
	return file_matchx_match_unity_qualify_proto_rawDescGZIP(), []int{3}
}

func (x *UnityQualifyRoomMember) GetAiLevel() int32 {
	if x != nil {
		return x.AiLevel
	}
	return 0
}

func (x *UnityQualifyRoomMember) GetTeamBroadcastId() int64 {
	if x != nil {
		return x.TeamBroadcastId
	}
	return 0
}

func (x *UnityQualifyRoomMember) GetTeamBubbleId() int64 {
	if x != nil {
		return x.TeamBubbleId
	}
	return 0
}

func (x *UnityQualifyRoomMember) GetSuitId() int64 {
	if x != nil {
		return x.SuitId
	}
	return 0
}

func (x *UnityQualifyRoomMember) GetSuitChosen() int32 {
	if x != nil {
		return x.SuitChosen
	}
	return 0
}

func (x *UnityQualifyRoomMember) GetSkinIdList() []int64 {
	if x != nil {
		return x.SkinIdList
	}
	return nil
}

type UnityQualifyGroupMember struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State     int32 `protobuf:"varint,1,opt,name=state,proto3" json:"state,omitempty"` // 在队伍中状态。默认0准备好，1结算中，2未准备
	RingId    int64 `protobuf:"varint,2,opt,name=ring_id,json=ringId,proto3" json:"ring_id,omitempty"`
	PropId    int64 `protobuf:"varint,3,opt,name=prop_id,json=propId,proto3" json:"prop_id,omitempty"`
	SkinId    int64 `protobuf:"varint,4,opt,name=skin_id,json=skinId,proto3" json:"skin_id,omitempty"`          // 皮肤 id
	SuitId    int64 `protobuf:"varint,5,opt,name=suit_id,json=suitId,proto3" json:"suit_id,omitempty"`          // 队服 id
	ShowValue int64 `protobuf:"varint,6,opt,name=show_value,json=showValue,proto3" json:"show_value,omitempty"` // show 值
}

func (x *UnityQualifyGroupMember) Reset() {
	*x = UnityQualifyGroupMember{}
	if protoimpl.UnsafeEnabled {
		mi := &file_matchx_match_unity_qualify_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnityQualifyGroupMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnityQualifyGroupMember) ProtoMessage() {}

func (x *UnityQualifyGroupMember) ProtoReflect() protoreflect.Message {
	mi := &file_matchx_match_unity_qualify_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnityQualifyGroupMember.ProtoReflect.Descriptor instead.
func (*UnityQualifyGroupMember) Descriptor() ([]byte, []int) {
	return file_matchx_match_unity_qualify_proto_rawDescGZIP(), []int{4}
}

func (x *UnityQualifyGroupMember) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *UnityQualifyGroupMember) GetRingId() int64 {
	if x != nil {
		return x.RingId
	}
	return 0
}

func (x *UnityQualifyGroupMember) GetPropId() int64 {
	if x != nil {
		return x.PropId
	}
	return 0
}

func (x *UnityQualifyGroupMember) GetSkinId() int64 {
	if x != nil {
		return x.SkinId
	}
	return 0
}

func (x *UnityQualifyGroupMember) GetSuitId() int64 {
	if x != nil {
		return x.SuitId
	}
	return 0
}

func (x *UnityQualifyGroupMember) GetShowValue() int64 {
	if x != nil {
		return x.ShowValue
	}
	return 0
}

type UnityQualifySyncGroupMemberNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MaxStar int64 `protobuf:"varint,1,opt,name=max_star,json=maxStar,proto3" json:"max_star,omitempty"`
}

func (x *UnityQualifySyncGroupMemberNotify) Reset() {
	*x = UnityQualifySyncGroupMemberNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_matchx_match_unity_qualify_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnityQualifySyncGroupMemberNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnityQualifySyncGroupMemberNotify) ProtoMessage() {}

func (x *UnityQualifySyncGroupMemberNotify) ProtoReflect() protoreflect.Message {
	mi := &file_matchx_match_unity_qualify_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnityQualifySyncGroupMemberNotify.ProtoReflect.Descriptor instead.
func (*UnityQualifySyncGroupMemberNotify) Descriptor() ([]byte, []int) {
	return file_matchx_match_unity_qualify_proto_rawDescGZIP(), []int{5}
}

func (x *UnityQualifySyncGroupMemberNotify) GetMaxStar() int64 {
	if x != nil {
		return x.MaxStar
	}
	return 0
}

var File_matchx_match_unity_qualify_proto protoreflect.FileDescriptor

var file_matchx_match_unity_qualify_proto_rawDesc = []byte{
	0x0a, 0x20, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x78, 0x2f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x2f, 0x75,
	0x6e, 0x69, 0x74, 0x79, 0x5f, 0x71, 0x75, 0x61, 0x6c, 0x69, 0x66, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x22, 0xdf, 0x01, 0x0a, 0x16, 0x55, 0x6e,
	0x69, 0x74, 0x79, 0x51, 0x75, 0x61, 0x6c, 0x69, 0x66, 0x79, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x41, 0x74, 0x74, 0x72, 0x12, 0x20, 0x0a, 0x0c, 0x73, 0x6b, 0x69, 0x6e, 0x5f, 0x69, 0x64, 0x5f,
	0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x0a, 0x73, 0x6b, 0x69, 0x6e,
	0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x75, 0x69, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x75, 0x69, 0x74, 0x49, 0x64, 0x12,
	0x2a, 0x0a, 0x11, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x62, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x74, 0x65, 0x61, 0x6d,
	0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0e, 0x74,
	0x65, 0x61, 0x6d, 0x5f, 0x62, 0x75, 0x62, 0x62, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0c, 0x74, 0x65, 0x61, 0x6d, 0x42, 0x75, 0x62, 0x62, 0x6c, 0x65, 0x49,
	0x64, 0x12, 0x38, 0x0a, 0x0f, 0x73, 0x6b, 0x69, 0x6e, 0x5f, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x5f,
	0x6c, 0x69, 0x73, 0x74, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x61, 0x74,
	0x63, 0x68, 0x2e, 0x53, 0x6b, 0x69, 0x6e, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x52, 0x0d, 0x73, 0x6b,
	0x69, 0x6e, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x17, 0x0a, 0x15, 0x52,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x79, 0x22, 0x40, 0x0a, 0x09, 0x53, 0x6b, 0x69, 0x6e, 0x53, 0x6b, 0x69, 0x6c,
	0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0xe1, 0x01, 0x0a, 0x16, 0x55, 0x6e, 0x69, 0x74, 0x79,
	0x51, 0x75, 0x61, 0x6c, 0x69, 0x66, 0x79, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x69, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x61, 0x69, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x2a, 0x0a, 0x11,
	0x74, 0x65, 0x61, 0x6d, 0x5f, 0x62, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x74, 0x65, 0x61, 0x6d, 0x42, 0x72, 0x6f,
	0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0e, 0x74, 0x65, 0x61, 0x6d,
	0x5f, 0x62, 0x75, 0x62, 0x62, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0c, 0x74, 0x65, 0x61, 0x6d, 0x42, 0x75, 0x62, 0x62, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x17,
	0x0a, 0x07, 0x73, 0x75, 0x69, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x73, 0x75, 0x69, 0x74, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x75, 0x69, 0x74, 0x5f,
	0x63, 0x68, 0x6f, 0x73, 0x65, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x75,
	0x69, 0x74, 0x43, 0x68, 0x6f, 0x73, 0x65, 0x6e, 0x12, 0x20, 0x0a, 0x0c, 0x73, 0x6b, 0x69, 0x6e,
	0x5f, 0x69, 0x64, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x06, 0x20, 0x03, 0x28, 0x03, 0x52, 0x0a,
	0x73, 0x6b, 0x69, 0x6e, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x22, 0xb2, 0x01, 0x0a, 0x17, 0x55,
	0x6e, 0x69, 0x74, 0x79, 0x51, 0x75, 0x61, 0x6c, 0x69, 0x66, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x17, 0x0a, 0x07,
	0x72, 0x69, 0x6e, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72,
	0x69, 0x6e, 0x67, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x70, 0x5f, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x70, 0x72, 0x6f, 0x70, 0x49, 0x64, 0x12, 0x17,
	0x0a, 0x07, 0x73, 0x6b, 0x69, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x73, 0x6b, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x75, 0x69, 0x74, 0x5f,
	0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x75, 0x69, 0x74, 0x49, 0x64,
	0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x68, 0x6f, 0x77, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x68, 0x6f, 0x77, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22,
	0x3e, 0x0a, 0x21, 0x55, 0x6e, 0x69, 0x74, 0x79, 0x51, 0x75, 0x61, 0x6c, 0x69, 0x66, 0x79, 0x53,
	0x79, 0x6e, 0x63, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x61, 0x78, 0x5f, 0x73, 0x74, 0x61, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6d, 0x61, 0x78, 0x53, 0x74, 0x61, 0x72, 0x42,
	0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x2e, 0x31, 0x37, 0x7a, 0x6a, 0x68, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x73, 0x6e, 0x61, 0x6b, 0x65, 0x2f, 0x73, 0x6e, 0x61, 0x6b, 0x65, 0x5f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x78, 0x2f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_matchx_match_unity_qualify_proto_rawDescOnce sync.Once
	file_matchx_match_unity_qualify_proto_rawDescData = file_matchx_match_unity_qualify_proto_rawDesc
)

func file_matchx_match_unity_qualify_proto_rawDescGZIP() []byte {
	file_matchx_match_unity_qualify_proto_rawDescOnce.Do(func() {
		file_matchx_match_unity_qualify_proto_rawDescData = protoimpl.X.CompressGZIP(file_matchx_match_unity_qualify_proto_rawDescData)
	})
	return file_matchx_match_unity_qualify_proto_rawDescData
}

var file_matchx_match_unity_qualify_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_matchx_match_unity_qualify_proto_goTypes = []interface{}{
	(*UnityQualifyUploadAttr)(nil),            // 0: match.UnityQualifyUploadAttr
	(*ReportRoomScoreNotify)(nil),             // 1: match.ReportRoomScoreNotify
	(*SkinSkill)(nil),                         // 2: match.SkinSkill
	(*UnityQualifyRoomMember)(nil),            // 3: match.UnityQualifyRoomMember
	(*UnityQualifyGroupMember)(nil),           // 4: match.UnityQualifyGroupMember
	(*UnityQualifySyncGroupMemberNotify)(nil), // 5: match.UnityQualifySyncGroupMemberNotify
}
var file_matchx_match_unity_qualify_proto_depIdxs = []int32{
	2, // 0: match.UnityQualifyUploadAttr.skin_skill_list:type_name -> match.SkinSkill
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_matchx_match_unity_qualify_proto_init() }
func file_matchx_match_unity_qualify_proto_init() {
	if File_matchx_match_unity_qualify_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_matchx_match_unity_qualify_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnityQualifyUploadAttr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_matchx_match_unity_qualify_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReportRoomScoreNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_matchx_match_unity_qualify_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SkinSkill); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_matchx_match_unity_qualify_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnityQualifyRoomMember); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_matchx_match_unity_qualify_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnityQualifyGroupMember); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_matchx_match_unity_qualify_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnityQualifySyncGroupMemberNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_matchx_match_unity_qualify_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_matchx_match_unity_qualify_proto_goTypes,
		DependencyIndexes: file_matchx_match_unity_qualify_proto_depIdxs,
		MessageInfos:      file_matchx_match_unity_qualify_proto_msgTypes,
	}.Build()
	File_matchx_match_unity_qualify_proto = out.File
	file_matchx_match_unity_qualify_proto_rawDesc = nil
	file_matchx_match_unity_qualify_proto_goTypes = nil
	file_matchx_match_unity_qualify_proto_depIdxs = nil
}
