// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.16.1
// source: snakecommon/activity_config.proto

package snakecommon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FarmConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActId             string          `protobuf:"bytes,1,opt,name=act_id,json=actId,proto3" json:"act_id,omitempty"`                                          // 活动id
	LinkUrl           string          `protobuf:"bytes,2,opt,name=link_url,json=linkUrl,proto3" json:"link_url,omitempty"`                                    // 玩法链接
	StartTime         int64           `protobuf:"varint,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`                             // 开始时间
	EndTime           int64           `protobuf:"varint,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`                                   // 结束时间
	UnlockNeedSkinNum int32           `protobuf:"varint,5,opt,name=unlock_need_skin_num,json=unlockNeedSkinNum,proto3" json:"unlock_need_skin_num,omitempty"` // 解锁玩法需要的皮肤数量
	HomePrompt        *FarmHomePrompt `protobuf:"bytes,6,opt,name=home_prompt,json=homePrompt,proto3" json:"home_prompt,omitempty"`                           // 首页提示
	BubbleIntervalSec int64           `protobuf:"varint,7,opt,name=bubble_interval_sec,json=bubbleIntervalSec,proto3" json:"bubble_interval_sec,omitempty"`   // 首页气泡提示间隔时间
}

func (x *FarmConfig) Reset() {
	*x = FarmConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snakecommon_activity_config_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FarmConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FarmConfig) ProtoMessage() {}

func (x *FarmConfig) ProtoReflect() protoreflect.Message {
	mi := &file_snakecommon_activity_config_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FarmConfig.ProtoReflect.Descriptor instead.
func (*FarmConfig) Descriptor() ([]byte, []int) {
	return file_snakecommon_activity_config_proto_rawDescGZIP(), []int{0}
}

func (x *FarmConfig) GetActId() string {
	if x != nil {
		return x.ActId
	}
	return ""
}

func (x *FarmConfig) GetLinkUrl() string {
	if x != nil {
		return x.LinkUrl
	}
	return ""
}

func (x *FarmConfig) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *FarmConfig) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *FarmConfig) GetUnlockNeedSkinNum() int32 {
	if x != nil {
		return x.UnlockNeedSkinNum
	}
	return 0
}

func (x *FarmConfig) GetHomePrompt() *FarmHomePrompt {
	if x != nil {
		return x.HomePrompt
	}
	return nil
}

func (x *FarmConfig) GetBubbleIntervalSec() int64 {
	if x != nil {
		return x.BubbleIntervalSec
	}
	return 0
}

type FarmHomePrompt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OpenSwitch    bool   `protobuf:"varint,1,opt,name=open_switch,json=openSwitch,proto3" json:"open_switch,omitempty"`         // 强引导开关
	UnlockContent string `protobuf:"bytes,2,opt,name=unlock_content,json=unlockContent,proto3" json:"unlock_content,omitempty"` // 解锁引导内容
}

func (x *FarmHomePrompt) Reset() {
	*x = FarmHomePrompt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snakecommon_activity_config_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FarmHomePrompt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FarmHomePrompt) ProtoMessage() {}

func (x *FarmHomePrompt) ProtoReflect() protoreflect.Message {
	mi := &file_snakecommon_activity_config_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FarmHomePrompt.ProtoReflect.Descriptor instead.
func (*FarmHomePrompt) Descriptor() ([]byte, []int) {
	return file_snakecommon_activity_config_proto_rawDescGZIP(), []int{1}
}

func (x *FarmHomePrompt) GetOpenSwitch() bool {
	if x != nil {
		return x.OpenSwitch
	}
	return false
}

func (x *FarmHomePrompt) GetUnlockContent() string {
	if x != nil {
		return x.UnlockContent
	}
	return ""
}

type MagicSkinConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartTime int64            `protobuf:"varint,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime   int64            `protobuf:"varint,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	BtnLink   string           `protobuf:"bytes,3,opt,name=btn_link,json=btnLink,proto3" json:"btn_link,omitempty"`
	Data      []*MagicSkinData `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *MagicSkinConfig) Reset() {
	*x = MagicSkinConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snakecommon_activity_config_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MagicSkinConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MagicSkinConfig) ProtoMessage() {}

func (x *MagicSkinConfig) ProtoReflect() protoreflect.Message {
	mi := &file_snakecommon_activity_config_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MagicSkinConfig.ProtoReflect.Descriptor instead.
func (*MagicSkinConfig) Descriptor() ([]byte, []int) {
	return file_snakecommon_activity_config_proto_rawDescGZIP(), []int{2}
}

func (x *MagicSkinConfig) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *MagicSkinConfig) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *MagicSkinConfig) GetBtnLink() string {
	if x != nil {
		return x.BtnLink
	}
	return ""
}

func (x *MagicSkinConfig) GetData() []*MagicSkinData {
	if x != nil {
		return x.Data
	}
	return nil
}

type MagicSkinData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActId     string `protobuf:"bytes,1,opt,name=act_id,json=actId,proto3" json:"act_id,omitempty"`              // 活动id
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                             // 活动名称
	ImgUrl    string `protobuf:"bytes,3,opt,name=img_url,json=imgUrl,proto3" json:"img_url,omitempty"`           // 活动图片
	StartTime int64  `protobuf:"varint,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // 开始时间
	EndTime   int64  `protobuf:"varint,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`       // 结束时间
}

func (x *MagicSkinData) Reset() {
	*x = MagicSkinData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snakecommon_activity_config_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MagicSkinData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MagicSkinData) ProtoMessage() {}

func (x *MagicSkinData) ProtoReflect() protoreflect.Message {
	mi := &file_snakecommon_activity_config_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MagicSkinData.ProtoReflect.Descriptor instead.
func (*MagicSkinData) Descriptor() ([]byte, []int) {
	return file_snakecommon_activity_config_proto_rawDescGZIP(), []int{3}
}

func (x *MagicSkinData) GetActId() string {
	if x != nil {
		return x.ActId
	}
	return ""
}

func (x *MagicSkinData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MagicSkinData) GetImgUrl() string {
	if x != nil {
		return x.ImgUrl
	}
	return ""
}

func (x *MagicSkinData) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *MagicSkinData) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type SnakeAreaConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActId        string `protobuf:"bytes,1,opt,name=act_id,json=actId,proto3" json:"act_id,omitempty"`                       // 活动id
	StartTime    int64  `protobuf:"varint,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`          // 开始时间
	EndTime      int64  `protobuf:"varint,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`                // 结束时间
	TargetLength int64  `protobuf:"varint,4,opt,name=target_length,json=targetLength,proto3" json:"target_length,omitempty"` // 达成挑战的目标长度
	RewardIcon   string `protobuf:"bytes,5,opt,name=reward_icon,json=rewardIcon,proto3" json:"reward_icon,omitempty"`        // 奖励icon
}

func (x *SnakeAreaConfig) Reset() {
	*x = SnakeAreaConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snakecommon_activity_config_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SnakeAreaConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnakeAreaConfig) ProtoMessage() {}

func (x *SnakeAreaConfig) ProtoReflect() protoreflect.Message {
	mi := &file_snakecommon_activity_config_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnakeAreaConfig.ProtoReflect.Descriptor instead.
func (*SnakeAreaConfig) Descriptor() ([]byte, []int) {
	return file_snakecommon_activity_config_proto_rawDescGZIP(), []int{4}
}

func (x *SnakeAreaConfig) GetActId() string {
	if x != nil {
		return x.ActId
	}
	return ""
}

func (x *SnakeAreaConfig) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *SnakeAreaConfig) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *SnakeAreaConfig) GetTargetLength() int64 {
	if x != nil {
		return x.TargetLength
	}
	return 0
}

func (x *SnakeAreaConfig) GetRewardIcon() string {
	if x != nil {
		return x.RewardIcon
	}
	return ""
}

var File_snakecommon_activity_config_proto protoreflect.FileDescriptor

var file_snakecommon_activity_config_proto_rawDesc = []byte{
	0x0a, 0x21, 0x73, 0x6e, 0x61, 0x6b, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x61, 0x63,
	0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x73, 0x6e, 0x61, 0x6b, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x1a, 0x18, 0x73, 0x6e, 0x61, 0x6b, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x97, 0x02, 0x0a, 0x0a, 0x46,
	0x61, 0x72, 0x6d, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x63, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x63, 0x74, 0x49, 0x64,
	0x12, 0x19, 0x0a, 0x08, 0x6c, 0x69, 0x6e, 0x6b, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6c, 0x69, 0x6e, 0x6b, 0x55, 0x72, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e,
	0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x65, 0x6e,
	0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x2f, 0x0a, 0x14, 0x75, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x5f,
	0x6e, 0x65, 0x65, 0x64, 0x5f, 0x73, 0x6b, 0x69, 0x6e, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x11, 0x75, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x65, 0x65, 0x64, 0x53,
	0x6b, 0x69, 0x6e, 0x4e, 0x75, 0x6d, 0x12, 0x3c, 0x0a, 0x0b, 0x68, 0x6f, 0x6d, 0x65, 0x5f, 0x70,
	0x72, 0x6f, 0x6d, 0x70, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x73, 0x6e,
	0x61, 0x6b, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x46, 0x61, 0x72, 0x6d, 0x48, 0x6f,
	0x6d, 0x65, 0x50, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x52, 0x0a, 0x68, 0x6f, 0x6d, 0x65, 0x50, 0x72,
	0x6f, 0x6d, 0x70, 0x74, 0x12, 0x2e, 0x0a, 0x13, 0x62, 0x75, 0x62, 0x62, 0x6c, 0x65, 0x5f, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x5f, 0x73, 0x65, 0x63, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x11, 0x62, 0x75, 0x62, 0x62, 0x6c, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61,
	0x6c, 0x53, 0x65, 0x63, 0x22, 0x58, 0x0a, 0x0e, 0x46, 0x61, 0x72, 0x6d, 0x48, 0x6f, 0x6d, 0x65,
	0x50, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x6f, 0x70, 0x65, 0x6e, 0x5f, 0x73,
	0x77, 0x69, 0x74, 0x63, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x6f, 0x70, 0x65,
	0x6e, 0x53, 0x77, 0x69, 0x74, 0x63, 0x68, 0x12, 0x25, 0x0a, 0x0e, 0x75, 0x6e, 0x6c, 0x6f, 0x63,
	0x6b, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x75, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x96,
	0x01, 0x0a, 0x0f, 0x4d, 0x61, 0x67, 0x69, 0x63, 0x53, 0x6b, 0x69, 0x6e, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08,
	0x62, 0x74, 0x6e, 0x5f, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x62, 0x74, 0x6e, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x2e, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x73, 0x6e, 0x61, 0x6b, 0x65, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x4d, 0x61, 0x67, 0x69, 0x63, 0x53, 0x6b, 0x69, 0x6e, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x8d, 0x01, 0x0a, 0x0d, 0x4d, 0x61, 0x67, 0x69,
	0x63, 0x53, 0x6b, 0x69, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x63, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x63, 0x74, 0x49, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x6d, 0x67, 0x5f, 0x75, 0x72, 0x6c, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x6d, 0x67, 0x55, 0x72, 0x6c, 0x12, 0x1d, 0x0a,
	0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08,
	0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07,
	0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x22, 0xa8, 0x01, 0x0a, 0x0f, 0x53, 0x6e, 0x61, 0x6b,
	0x65, 0x41, 0x72, 0x65, 0x61, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x15, 0x0a, 0x06, 0x61,
	0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x63, 0x74,
	0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0c, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4c, 0x65, 0x6e, 0x67, 0x74,
	0x68, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x5f, 0x69, 0x63, 0x6f, 0x6e,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x49, 0x63,
	0x6f, 0x6e, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x2e, 0x31, 0x37, 0x7a, 0x6a, 0x68, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x6e, 0x61, 0x6b, 0x65, 0x2f, 0x73, 0x6e, 0x61, 0x6b, 0x65, 0x5f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x6e, 0x61, 0x6b, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_snakecommon_activity_config_proto_rawDescOnce sync.Once
	file_snakecommon_activity_config_proto_rawDescData = file_snakecommon_activity_config_proto_rawDesc
)

func file_snakecommon_activity_config_proto_rawDescGZIP() []byte {
	file_snakecommon_activity_config_proto_rawDescOnce.Do(func() {
		file_snakecommon_activity_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_snakecommon_activity_config_proto_rawDescData)
	})
	return file_snakecommon_activity_config_proto_rawDescData
}

var file_snakecommon_activity_config_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_snakecommon_activity_config_proto_goTypes = []interface{}{
	(*FarmConfig)(nil),      // 0: snakecommon.FarmConfig
	(*FarmHomePrompt)(nil),  // 1: snakecommon.FarmHomePrompt
	(*MagicSkinConfig)(nil), // 2: snakecommon.MagicSkinConfig
	(*MagicSkinData)(nil),   // 3: snakecommon.MagicSkinData
	(*SnakeAreaConfig)(nil), // 4: snakecommon.SnakeAreaConfig
}
var file_snakecommon_activity_config_proto_depIdxs = []int32{
	1, // 0: snakecommon.FarmConfig.home_prompt:type_name -> snakecommon.FarmHomePrompt
	3, // 1: snakecommon.MagicSkinConfig.data:type_name -> snakecommon.MagicSkinData
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_snakecommon_activity_config_proto_init() }
func file_snakecommon_activity_config_proto_init() {
	if File_snakecommon_activity_config_proto != nil {
		return
	}
	file_snakecommon_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_snakecommon_activity_config_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FarmConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snakecommon_activity_config_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FarmHomePrompt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snakecommon_activity_config_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MagicSkinConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snakecommon_activity_config_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MagicSkinData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snakecommon_activity_config_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SnakeAreaConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_snakecommon_activity_config_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_snakecommon_activity_config_proto_goTypes,
		DependencyIndexes: file_snakecommon_activity_config_proto_depIdxs,
		MessageInfos:      file_snakecommon_activity_config_proto_msgTypes,
	}.Build()
	File_snakecommon_activity_config_proto = out.File
	file_snakecommon_activity_config_proto_rawDesc = nil
	file_snakecommon_activity_config_proto_goTypes = nil
	file_snakecommon_activity_config_proto_depIdxs = nil
}
