// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.16.1
// source: snakecommon/common.proto

package snakecommon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HttpCommRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg     string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data    []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Time    int32  `protobuf:"varint,4,opt,name=time,proto3" json:"time,omitempty"`
	TraceId string `protobuf:"bytes,5,opt,name=traceId,proto3" json:"traceId,omitempty"`
}

func (x *HttpCommRsp) Reset() {
	*x = HttpCommRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snakecommon_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HttpCommRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpCommRsp) ProtoMessage() {}

func (x *HttpCommRsp) ProtoReflect() protoreflect.Message {
	mi := &file_snakecommon_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpCommRsp.ProtoReflect.Descriptor instead.
func (*HttpCommRsp) Descriptor() ([]byte, []int) {
	return file_snakecommon_common_proto_rawDescGZIP(), []int{0}
}

func (x *HttpCommRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *HttpCommRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *HttpCommRsp) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *HttpCommRsp) GetTime() int32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *HttpCommRsp) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

// 空返回
type EmptyRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyRsp) Reset() {
	*x = EmptyRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snakecommon_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRsp) ProtoMessage() {}

func (x *EmptyRsp) ProtoReflect() protoreflect.Message {
	mi := &file_snakecommon_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRsp.ProtoReflect.Descriptor instead.
func (*EmptyRsp) Descriptor() ([]byte, []int) {
	return file_snakecommon_common_proto_rawDescGZIP(), []int{1}
}

// loading页配置
type LoadingConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BackgroundAnimation []string `protobuf:"bytes,1,rep,name=background_animation,json=backgroundAnimation,proto3" json:"background_animation,omitempty"` // 背景动效
	LoadingAnimation    []string `protobuf:"bytes,2,rep,name=loading_animation,json=loadingAnimation,proto3" json:"loading_animation,omitempty"`          // loading动效
	ActivityText        []string `protobuf:"bytes,3,rep,name=activity_text,json=activityText,proto3" json:"activity_text,omitempty"`                      // 活动文案
	BaseText            []string `protobuf:"bytes,4,rep,name=base_text,json=baseText,proto3" json:"base_text,omitempty"`                                  // 兜底文案
}

func (x *LoadingConfig) Reset() {
	*x = LoadingConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snakecommon_common_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadingConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadingConfig) ProtoMessage() {}

func (x *LoadingConfig) ProtoReflect() protoreflect.Message {
	mi := &file_snakecommon_common_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadingConfig.ProtoReflect.Descriptor instead.
func (*LoadingConfig) Descriptor() ([]byte, []int) {
	return file_snakecommon_common_proto_rawDescGZIP(), []int{2}
}

func (x *LoadingConfig) GetBackgroundAnimation() []string {
	if x != nil {
		return x.BackgroundAnimation
	}
	return nil
}

func (x *LoadingConfig) GetLoadingAnimation() []string {
	if x != nil {
		return x.LoadingAnimation
	}
	return nil
}

func (x *LoadingConfig) GetActivityText() []string {
	if x != nil {
		return x.ActivityText
	}
	return nil
}

func (x *LoadingConfig) GetBaseText() []string {
	if x != nil {
		return x.BaseText
	}
	return nil
}

type PVConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AnimType       int32  `protobuf:"varint,2,opt,name=anim_type,json=animType,proto3" json:"anim_type,omitempty"`
	AnimUrl        string `protobuf:"bytes,3,opt,name=anim_url,json=animUrl,proto3" json:"anim_url,omitempty"`
	Times          int32  `protobuf:"varint,4,opt,name=times,proto3" json:"times,omitempty"`
	ForceWatchTime int32  `protobuf:"varint,5,opt,name=force_watch_time,json=forceWatchTime,proto3" json:"force_watch_time,omitempty"`
}

func (x *PVConfig) Reset() {
	*x = PVConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snakecommon_common_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PVConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PVConfig) ProtoMessage() {}

func (x *PVConfig) ProtoReflect() protoreflect.Message {
	mi := &file_snakecommon_common_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PVConfig.ProtoReflect.Descriptor instead.
func (*PVConfig) Descriptor() ([]byte, []int) {
	return file_snakecommon_common_proto_rawDescGZIP(), []int{3}
}

func (x *PVConfig) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PVConfig) GetAnimType() int32 {
	if x != nil {
		return x.AnimType
	}
	return 0
}

func (x *PVConfig) GetAnimUrl() string {
	if x != nil {
		return x.AnimUrl
	}
	return ""
}

func (x *PVConfig) GetTimes() int32 {
	if x != nil {
		return x.Times
	}
	return 0
}

func (x *PVConfig) GetForceWatchTime() int32 {
	if x != nil {
		return x.ForceWatchTime
	}
	return 0
}

type FollowerTopListTipsConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tips string `protobuf:"bytes,1,opt,name=tips,proto3" json:"tips,omitempty"`
}

func (x *FollowerTopListTipsConfig) Reset() {
	*x = FollowerTopListTipsConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snakecommon_common_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FollowerTopListTipsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowerTopListTipsConfig) ProtoMessage() {}

func (x *FollowerTopListTipsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_snakecommon_common_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowerTopListTipsConfig.ProtoReflect.Descriptor instead.
func (*FollowerTopListTipsConfig) Descriptor() ([]byte, []int) {
	return file_snakecommon_common_proto_rawDescGZIP(), []int{4}
}

func (x *FollowerTopListTipsConfig) GetTips() string {
	if x != nil {
		return x.Tips
	}
	return ""
}

var File_snakecommon_common_proto protoreflect.FileDescriptor

var file_snakecommon_common_proto_rawDesc = []byte{
	0x0a, 0x18, 0x73, 0x6e, 0x61, 0x6b, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x73, 0x6e, 0x61, 0x6b,
	0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x22, 0x75, 0x0a, 0x0b, 0x48, 0x74, 0x74, 0x70, 0x43,
	0x6f, 0x6d, 0x6d, 0x52, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x74, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x72, 0x61, 0x63, 0x65, 0x49, 0x64, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x72, 0x61, 0x63, 0x65, 0x49, 0x64, 0x22, 0x0a,
	0x0a, 0x08, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x73, 0x70, 0x22, 0xb1, 0x01, 0x0a, 0x0d, 0x4c,
	0x6f, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x31, 0x0a, 0x14,
	0x62, 0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x5f, 0x61, 0x6e, 0x69, 0x6d, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x13, 0x62, 0x61, 0x63, 0x6b,
	0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x2b, 0x0a, 0x11, 0x6c, 0x6f, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x61, 0x6e, 0x69, 0x6d, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x10, 0x6c, 0x6f, 0x61, 0x64,
	0x69, 0x6e, 0x67, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x23, 0x0a, 0x0d,
	0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x54, 0x65, 0x78,
	0x74, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x62, 0x61, 0x73, 0x65, 0x54, 0x65, 0x78, 0x74, 0x22, 0x92,
	0x01, 0x0a, 0x08, 0x50, 0x56, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x61,
	0x6e, 0x69, 0x6d, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x61, 0x6e, 0x69, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x6e, 0x69, 0x6d,
	0x5f, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x6e, 0x69, 0x6d,
	0x55, 0x72, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x12, 0x28, 0x0a, 0x10, 0x66, 0x6f, 0x72,
	0x63, 0x65, 0x5f, 0x77, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0e, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x57, 0x61, 0x74, 0x63, 0x68, 0x54,
	0x69, 0x6d, 0x65, 0x22, 0x2f, 0x0a, 0x19, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x54,
	0x6f, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x69, 0x70, 0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x70, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x69, 0x70, 0x73, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x2e, 0x31, 0x37, 0x7a, 0x6a,
	0x68, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x6e, 0x61, 0x6b, 0x65, 0x2f, 0x73, 0x6e, 0x61, 0x6b,
	0x65, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x6e, 0x61, 0x6b, 0x65, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_snakecommon_common_proto_rawDescOnce sync.Once
	file_snakecommon_common_proto_rawDescData = file_snakecommon_common_proto_rawDesc
)

func file_snakecommon_common_proto_rawDescGZIP() []byte {
	file_snakecommon_common_proto_rawDescOnce.Do(func() {
		file_snakecommon_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_snakecommon_common_proto_rawDescData)
	})
	return file_snakecommon_common_proto_rawDescData
}

var file_snakecommon_common_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_snakecommon_common_proto_goTypes = []interface{}{
	(*HttpCommRsp)(nil),               // 0: snakecommon.HttpCommRsp
	(*EmptyRsp)(nil),                  // 1: snakecommon.EmptyRsp
	(*LoadingConfig)(nil),             // 2: snakecommon.LoadingConfig
	(*PVConfig)(nil),                  // 3: snakecommon.PVConfig
	(*FollowerTopListTipsConfig)(nil), // 4: snakecommon.FollowerTopListTipsConfig
}
var file_snakecommon_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_snakecommon_common_proto_init() }
func file_snakecommon_common_proto_init() {
	if File_snakecommon_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_snakecommon_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HttpCommRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snakecommon_common_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snakecommon_common_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadingConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snakecommon_common_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PVConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snakecommon_common_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FollowerTopListTipsConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_snakecommon_common_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_snakecommon_common_proto_goTypes,
		DependencyIndexes: file_snakecommon_common_proto_depIdxs,
		MessageInfos:      file_snakecommon_common_proto_msgTypes,
	}.Build()
	File_snakecommon_common_proto = out.File
	file_snakecommon_common_proto_rawDesc = nil
	file_snakecommon_common_proto_goTypes = nil
	file_snakecommon_common_proto_depIdxs = nil
}
