// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: snakecommon/common.proto

package snakecommon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HttpCommRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg     string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data    []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Time    int32  `protobuf:"varint,4,opt,name=time,proto3" json:"time,omitempty"`
	TraceId string `protobuf:"bytes,5,opt,name=traceId,proto3" json:"traceId,omitempty"`
}

func (x *HttpCommRsp) Reset() {
	*x = HttpCommRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snakecommon_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HttpCommRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpCommRsp) ProtoMessage() {}

func (x *HttpCommRsp) ProtoReflect() protoreflect.Message {
	mi := &file_snakecommon_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpCommRsp.ProtoReflect.Descriptor instead.
func (*HttpCommRsp) Descriptor() ([]byte, []int) {
	return file_snakecommon_common_proto_rawDescGZIP(), []int{0}
}

func (x *HttpCommRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *HttpCommRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *HttpCommRsp) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *HttpCommRsp) GetTime() int32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *HttpCommRsp) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

// 空返回
type EmptyRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyRsp) Reset() {
	*x = EmptyRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snakecommon_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRsp) ProtoMessage() {}

func (x *EmptyRsp) ProtoReflect() protoreflect.Message {
	mi := &file_snakecommon_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRsp.ProtoReflect.Descriptor instead.
func (*EmptyRsp) Descriptor() ([]byte, []int) {
	return file_snakecommon_common_proto_rawDescGZIP(), []int{1}
}

type ActivityBase struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActId       string `protobuf:"bytes,1,opt,name=act_id,json=actId,proto3" json:"act_id,omitempty"`
	StartTime   string `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime     string `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Desc        string `protobuf:"bytes,4,opt,name=desc,proto3" json:"desc,omitempty"`
	ActCenterId int32  `protobuf:"varint,5,opt,name=act_center_id,json=actCenterId,proto3" json:"act_center_id,omitempty"`
	DrawCardId  int32  `protobuf:"varint,6,opt,name=draw_card_id,json=drawCardId,proto3" json:"draw_card_id,omitempty"`
}

func (x *ActivityBase) Reset() {
	*x = ActivityBase{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snakecommon_common_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActivityBase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityBase) ProtoMessage() {}

func (x *ActivityBase) ProtoReflect() protoreflect.Message {
	mi := &file_snakecommon_common_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityBase.ProtoReflect.Descriptor instead.
func (*ActivityBase) Descriptor() ([]byte, []int) {
	return file_snakecommon_common_proto_rawDescGZIP(), []int{2}
}

func (x *ActivityBase) GetActId() string {
	if x != nil {
		return x.ActId
	}
	return ""
}

func (x *ActivityBase) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *ActivityBase) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *ActivityBase) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *ActivityBase) GetActCenterId() int32 {
	if x != nil {
		return x.ActCenterId
	}
	return 0
}

func (x *ActivityBase) GetDrawCardId() int32 {
	if x != nil {
		return x.DrawCardId
	}
	return 0
}

var File_snakecommon_common_proto protoreflect.FileDescriptor

var file_snakecommon_common_proto_rawDesc = []byte{
	0x0a, 0x18, 0x73, 0x6e, 0x61, 0x6b, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x73, 0x6e, 0x61, 0x6b,
	0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x22, 0x75, 0x0a, 0x0b, 0x48, 0x74, 0x74, 0x70, 0x43,
	0x6f, 0x6d, 0x6d, 0x52, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x74, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x72, 0x61, 0x63, 0x65, 0x49, 0x64, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x72, 0x61, 0x63, 0x65, 0x49, 0x64, 0x22, 0x0a,
	0x0a, 0x08, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x73, 0x70, 0x22, 0xb9, 0x01, 0x0a, 0x0c, 0x41,
	0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x42, 0x61, 0x73, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x61,
	0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x63, 0x74,
	0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x65, 0x73, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63,
	0x12, 0x22, 0x0a, 0x0d, 0x61, 0x63, 0x74, 0x5f, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x61, 0x63, 0x74, 0x43, 0x65, 0x6e, 0x74,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0c, 0x64, 0x72, 0x61, 0x77, 0x5f, 0x63, 0x61, 0x72,
	0x64, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x64, 0x72, 0x61, 0x77,
	0x43, 0x61, 0x72, 0x64, 0x49, 0x64, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x2e, 0x31, 0x37,
	0x7a, 0x6a, 0x68, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x6e, 0x61, 0x6b, 0x65, 0x2f, 0x73, 0x6e,
	0x61, 0x6b, 0x65, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x6e, 0x61, 0x6b, 0x65, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_snakecommon_common_proto_rawDescOnce sync.Once
	file_snakecommon_common_proto_rawDescData = file_snakecommon_common_proto_rawDesc
)

func file_snakecommon_common_proto_rawDescGZIP() []byte {
	file_snakecommon_common_proto_rawDescOnce.Do(func() {
		file_snakecommon_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_snakecommon_common_proto_rawDescData)
	})
	return file_snakecommon_common_proto_rawDescData
}

var file_snakecommon_common_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_snakecommon_common_proto_goTypes = []interface{}{
	(*HttpCommRsp)(nil),  // 0: snakecommon.HttpCommRsp
	(*EmptyRsp)(nil),     // 1: snakecommon.EmptyRsp
	(*ActivityBase)(nil), // 2: snakecommon.ActivityBase
}
var file_snakecommon_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_snakecommon_common_proto_init() }
func file_snakecommon_common_proto_init() {
	if File_snakecommon_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_snakecommon_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HttpCommRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snakecommon_common_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snakecommon_common_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActivityBase); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_snakecommon_common_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_snakecommon_common_proto_goTypes,
		DependencyIndexes: file_snakecommon_common_proto_depIdxs,
		MessageInfos:      file_snakecommon_common_proto_msgTypes,
	}.Build()
	File_snakecommon_common_proto = out.File
	file_snakecommon_common_proto_rawDesc = nil
	file_snakecommon_common_proto_goTypes = nil
	file_snakecommon_common_proto_depIdxs = nil
}
