// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.16.1
// source: fallguys/match.proto

package fallguys

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoomState int32

const (
	RoomState_Idle      RoomState = 0 // 空闲
	RoomState_WaitEnter RoomState = 1 // 待进入
	RoomState_InGame    RoomState = 2 // 游戏中
	RoomState_WaitExit  RoomState = 3 // 待退出
	RoomState_Offline   RoomState = 4 // 离线
)

// Enum value maps for RoomState.
var (
	RoomState_name = map[int32]string{
		0: "Idle",
		1: "WaitEnter",
		2: "InGame",
		3: "WaitExit",
		4: "Offline",
	}
	RoomState_value = map[string]int32{
		"Idle":      0,
		"WaitEnter": 1,
		"InGame":    2,
		"WaitExit":  3,
		"Offline":   4,
	}
)

func (x RoomState) Enum() *RoomState {
	p := new(RoomState)
	*p = x
	return p
}

func (x RoomState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomState) Descriptor() protoreflect.EnumDescriptor {
	return file_fallguys_match_proto_enumTypes[0].Descriptor()
}

func (RoomState) Type() protoreflect.EnumType {
	return &file_fallguys_match_proto_enumTypes[0]
}

func (x RoomState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoomState.Descriptor instead.
func (RoomState) EnumDescriptor() ([]byte, []int) {
	return file_fallguys_match_proto_rawDescGZIP(), []int{0}
}

// unity server每秒定时同步房间状态
type SyncStateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr        string    `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`                            // ip:端口
	Pid         int32     `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`                             // 进程id
	ModeVersion int32     `protobuf:"varint,3,opt,name=modeVersion,proto3" json:"modeVersion,omitempty"`             // 模式版本号
	State       RoomState `protobuf:"varint,4,opt,name=state,proto3,enum=fallguys.RoomState" json:"state,omitempty"` // 状态
}

func (x *SyncStateReq) Reset() {
	*x = SyncStateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fallguys_match_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncStateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncStateReq) ProtoMessage() {}

func (x *SyncStateReq) ProtoReflect() protoreflect.Message {
	mi := &file_fallguys_match_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncStateReq.ProtoReflect.Descriptor instead.
func (*SyncStateReq) Descriptor() ([]byte, []int) {
	return file_fallguys_match_proto_rawDescGZIP(), []int{0}
}

func (x *SyncStateReq) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *SyncStateReq) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *SyncStateReq) GetModeVersion() int32 {
	if x != nil {
		return x.ModeVersion
	}
	return 0
}

func (x *SyncStateReq) GetState() RoomState {
	if x != nil {
		return x.State
	}
	return RoomState_Idle
}

type SyncStateRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SyncStateRsp) Reset() {
	*x = SyncStateRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fallguys_match_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncStateRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncStateRsp) ProtoMessage() {}

func (x *SyncStateRsp) ProtoReflect() protoreflect.Message {
	mi := &file_fallguys_match_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncStateRsp.ProtoReflect.Descriptor instead.
func (*SyncStateRsp) Descriptor() ([]byte, []int) {
	return file_fallguys_match_proto_rawDescGZIP(), []int{1}
}

type Winner struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid  string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`    // 玩家uid
	Rank int32  `protobuf:"varint,2,opt,name=rank,proto3" json:"rank,omitempty"` // 名次
}

func (x *Winner) Reset() {
	*x = Winner{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fallguys_match_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Winner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Winner) ProtoMessage() {}

func (x *Winner) ProtoReflect() protoreflect.Message {
	mi := &file_fallguys_match_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Winner.ProtoReflect.Descriptor instead.
func (*Winner) Descriptor() ([]byte, []int) {
	return file_fallguys_match_proto_rawDescGZIP(), []int{2}
}

func (x *Winner) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Winner) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

// 游戏结束时untiy server通知游戏结果
type EndGameReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr    string    `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"` // ip:端口
	Rid     int32     `protobuf:"varint,2,opt,name=rid,proto3" json:"rid,omitempty"`
	Winners []*Winner `protobuf:"bytes,3,rep,name=winners,proto3" json:"winners,omitempty"`
}

func (x *EndGameReq) Reset() {
	*x = EndGameReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fallguys_match_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EndGameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndGameReq) ProtoMessage() {}

func (x *EndGameReq) ProtoReflect() protoreflect.Message {
	mi := &file_fallguys_match_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndGameReq.ProtoReflect.Descriptor instead.
func (*EndGameReq) Descriptor() ([]byte, []int) {
	return file_fallguys_match_proto_rawDescGZIP(), []int{3}
}

func (x *EndGameReq) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *EndGameReq) GetRid() int32 {
	if x != nil {
		return x.Rid
	}
	return 0
}

func (x *EndGameReq) GetWinners() []*Winner {
	if x != nil {
		return x.Winners
	}
	return nil
}

type EndGameRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EndGameRsp) Reset() {
	*x = EndGameRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fallguys_match_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EndGameRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndGameRsp) ProtoMessage() {}

func (x *EndGameRsp) ProtoReflect() protoreflect.Message {
	mi := &file_fallguys_match_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndGameRsp.ProtoReflect.Descriptor instead.
func (*EndGameRsp) Descriptor() ([]byte, []int) {
	return file_fallguys_match_proto_rawDescGZIP(), []int{4}
}

type SubscribeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"` // ip:端口
}

func (x *SubscribeReq) Reset() {
	*x = SubscribeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fallguys_match_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeReq) ProtoMessage() {}

func (x *SubscribeReq) ProtoReflect() protoreflect.Message {
	mi := &file_fallguys_match_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeReq.ProtoReflect.Descriptor instead.
func (*SubscribeReq) Descriptor() ([]byte, []int) {
	return file_fallguys_match_proto_rawDescGZIP(), []int{5}
}

func (x *SubscribeReq) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type SubscribeRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PushType PushType `protobuf:"varint,1,opt,name=pushType,proto3,enum=fallguys.PushType" json:"pushType,omitempty"` // push 类型
	Data     []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`                                 // push内容
	MsgId    string   `protobuf:"bytes,3,opt,name=msgId,proto3" json:"msgId,omitempty"`                               // 唯一标识
}

func (x *SubscribeRsp) Reset() {
	*x = SubscribeRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fallguys_match_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRsp) ProtoMessage() {}

func (x *SubscribeRsp) ProtoReflect() protoreflect.Message {
	mi := &file_fallguys_match_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRsp.ProtoReflect.Descriptor instead.
func (*SubscribeRsp) Descriptor() ([]byte, []int) {
	return file_fallguys_match_proto_rawDescGZIP(), []int{6}
}

func (x *SubscribeRsp) GetPushType() PushType {
	if x != nil {
		return x.PushType
	}
	return PushType_SyncGameInfo
}

func (x *SubscribeRsp) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SubscribeRsp) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

type GameReadyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ready bool   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`          // 是否初始化成功
	MsgId string `protobuf:"bytes,2,opt,name=msgId,proto3" json:"msgId,omitempty"`           // push消息中的唯一标识
	Addr  string `protobuf:"bytes,3,opt,name=addr,proto3" json:"addr,omitempty"`             // ip:端口
	DsId  string `protobuf:"bytes,4,opt,name=ds_id,json=dsId,proto3" json:"ds_id,omitempty"` // unity server id 标识
	Rid   int32  `protobuf:"varint,5,opt,name=rid,proto3" json:"rid,omitempty"`              // 房间 id
}

func (x *GameReadyReq) Reset() {
	*x = GameReadyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fallguys_match_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameReadyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameReadyReq) ProtoMessage() {}

func (x *GameReadyReq) ProtoReflect() protoreflect.Message {
	mi := &file_fallguys_match_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameReadyReq.ProtoReflect.Descriptor instead.
func (*GameReadyReq) Descriptor() ([]byte, []int) {
	return file_fallguys_match_proto_rawDescGZIP(), []int{7}
}

func (x *GameReadyReq) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *GameReadyReq) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *GameReadyReq) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *GameReadyReq) GetDsId() string {
	if x != nil {
		return x.DsId
	}
	return ""
}

func (x *GameReadyReq) GetRid() int32 {
	if x != nil {
		return x.Rid
	}
	return 0
}

type GameReadyRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GameReadyRsp) Reset() {
	*x = GameReadyRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fallguys_match_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameReadyRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameReadyRsp) ProtoMessage() {}

func (x *GameReadyRsp) ProtoReflect() protoreflect.Message {
	mi := &file_fallguys_match_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameReadyRsp.ProtoReflect.Descriptor instead.
func (*GameReadyRsp) Descriptor() ([]byte, []int) {
	return file_fallguys_match_proto_rawDescGZIP(), []int{8}
}

// 游戏每关结束时untiy server通知本轮游戏结果
type EndRoundReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr        string    `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`                          // ip:端口
	Rid         int32     `protobuf:"varint,2,opt,name=rid,proto3" json:"rid,omitempty"`                           // 房间id
	Winners     []*Winner `protobuf:"bytes,3,rep,name=winners,proto3" json:"winners,omitempty"`                    // 本轮淘汰的玩家的名次
	IsLastRound bool      `protobuf:"varint,4,opt,name=isLastRound,proto3" json:"isLastRound,omitempty"`           // 是否是最后一关
	RoundNum    int32     `protobuf:"varint,5,opt,name=round_num,json=roundNum,proto3" json:"round_num,omitempty"` // 当前关卡数，用来计算奖励系数
}

func (x *EndRoundReq) Reset() {
	*x = EndRoundReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fallguys_match_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EndRoundReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndRoundReq) ProtoMessage() {}

func (x *EndRoundReq) ProtoReflect() protoreflect.Message {
	mi := &file_fallguys_match_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndRoundReq.ProtoReflect.Descriptor instead.
func (*EndRoundReq) Descriptor() ([]byte, []int) {
	return file_fallguys_match_proto_rawDescGZIP(), []int{9}
}

func (x *EndRoundReq) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *EndRoundReq) GetRid() int32 {
	if x != nil {
		return x.Rid
	}
	return 0
}

func (x *EndRoundReq) GetWinners() []*Winner {
	if x != nil {
		return x.Winners
	}
	return nil
}

func (x *EndRoundReq) GetIsLastRound() bool {
	if x != nil {
		return x.IsLastRound
	}
	return false
}

func (x *EndRoundReq) GetRoundNum() int32 {
	if x != nil {
		return x.RoundNum
	}
	return 0
}

type EndRoundRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Players []*EndRoundPlayer `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
}

func (x *EndRoundRsp) Reset() {
	*x = EndRoundRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fallguys_match_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EndRoundRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndRoundRsp) ProtoMessage() {}

func (x *EndRoundRsp) ProtoReflect() protoreflect.Message {
	mi := &file_fallguys_match_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndRoundRsp.ProtoReflect.Descriptor instead.
func (*EndRoundRsp) Descriptor() ([]byte, []int) {
	return file_fallguys_match_proto_rawDescGZIP(), []int{10}
}

func (x *EndRoundRsp) GetPlayers() []*EndRoundPlayer {
	if x != nil {
		return x.Players
	}
	return nil
}

type EndRoundPlayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid        string        `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	RewardList []*RewardItem `protobuf:"bytes,2,rep,name=reward_list,json=rewardList,proto3" json:"reward_list,omitempty"`
}

func (x *EndRoundPlayer) Reset() {
	*x = EndRoundPlayer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fallguys_match_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EndRoundPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndRoundPlayer) ProtoMessage() {}

func (x *EndRoundPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_fallguys_match_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndRoundPlayer.ProtoReflect.Descriptor instead.
func (*EndRoundPlayer) Descriptor() ([]byte, []int) {
	return file_fallguys_match_proto_rawDescGZIP(), []int{11}
}

func (x *EndRoundPlayer) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *EndRoundPlayer) GetRewardList() []*RewardItem {
	if x != nil {
		return x.RewardList
	}
	return nil
}

type RewardItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type   int32  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`     // 奖励类型
	ItemId int32  `protobuf:"varint,2,opt,name=itemId,proto3" json:"itemId,omitempty"` // 道具id
	Num    int32  `protobuf:"varint,3,opt,name=num,proto3" json:"num,omitempty"`       // 数量
	Name   string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`      // 名称
	Imgurl string `protobuf:"bytes,5,opt,name=imgurl,proto3" json:"imgurl,omitempty"`  // 图片
}

func (x *RewardItem) Reset() {
	*x = RewardItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fallguys_match_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RewardItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewardItem) ProtoMessage() {}

func (x *RewardItem) ProtoReflect() protoreflect.Message {
	mi := &file_fallguys_match_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewardItem.ProtoReflect.Descriptor instead.
func (*RewardItem) Descriptor() ([]byte, []int) {
	return file_fallguys_match_proto_rawDescGZIP(), []int{12}
}

func (x *RewardItem) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *RewardItem) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *RewardItem) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *RewardItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RewardItem) GetImgurl() string {
	if x != nil {
		return x.Imgurl
	}
	return ""
}

type UploadMetricReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action   string           `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Uid      string           `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Rid      int32            `protobuf:"varint,3,opt,name=rid,proto3" json:"rid,omitempty"`
	Platform int32            `protobuf:"varint,4,opt,name=platform,proto3" json:"platform,omitempty"`
	Market   string           `protobuf:"bytes,5,opt,name=market,proto3" json:"market,omitempty"`
	Version  string           `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	Kvs      *structpb.Struct `protobuf:"bytes,7,opt,name=kvs,proto3" json:"kvs,omitempty"`
}

func (x *UploadMetricReq) Reset() {
	*x = UploadMetricReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fallguys_match_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadMetricReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMetricReq) ProtoMessage() {}

func (x *UploadMetricReq) ProtoReflect() protoreflect.Message {
	mi := &file_fallguys_match_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMetricReq.ProtoReflect.Descriptor instead.
func (*UploadMetricReq) Descriptor() ([]byte, []int) {
	return file_fallguys_match_proto_rawDescGZIP(), []int{13}
}

func (x *UploadMetricReq) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *UploadMetricReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *UploadMetricReq) GetRid() int32 {
	if x != nil {
		return x.Rid
	}
	return 0
}

func (x *UploadMetricReq) GetPlatform() int32 {
	if x != nil {
		return x.Platform
	}
	return 0
}

func (x *UploadMetricReq) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

func (x *UploadMetricReq) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *UploadMetricReq) GetKvs() *structpb.Struct {
	if x != nil {
		return x.Kvs
	}
	return nil
}

type UploadMetricRsq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UploadMetricRsq) Reset() {
	*x = UploadMetricRsq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fallguys_match_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadMetricRsq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMetricRsq) ProtoMessage() {}

func (x *UploadMetricRsq) ProtoReflect() protoreflect.Message {
	mi := &file_fallguys_match_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMetricRsq.ProtoReflect.Descriptor instead.
func (*UploadMetricRsq) Descriptor() ([]byte, []int) {
	return file_fallguys_match_proto_rawDescGZIP(), []int{14}
}

type GetAIListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num          int32           `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`                                                                                                                                // 需要的ai数量
	LevelVersion map[int32]int32 `protobuf:"bytes,2,rep,name=level_version,json=levelVersion,proto3" json:"level_version,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"` // {关卡id:关卡版本}
}

func (x *GetAIListReq) Reset() {
	*x = GetAIListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fallguys_match_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAIListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAIListReq) ProtoMessage() {}

func (x *GetAIListReq) ProtoReflect() protoreflect.Message {
	mi := &file_fallguys_match_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAIListReq.ProtoReflect.Descriptor instead.
func (*GetAIListReq) Descriptor() ([]byte, []int) {
	return file_fallguys_match_proto_rawDescGZIP(), []int{15}
}

func (x *GetAIListReq) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *GetAIListReq) GetLevelVersion() map[int32]int32 {
	if x != nil {
		return x.LevelVersion
	}
	return nil
}

type AIItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BornPos string `protobuf:"bytes,1,opt,name=born_pos,json=bornPos,proto3" json:"born_pos,omitempty"` // 起始点坐标
	AiUrl   string `protobuf:"bytes,2,opt,name=ai_url,json=aiUrl,proto3" json:"ai_url,omitempty"`       // ai数据链接
}

func (x *AIItem) Reset() {
	*x = AIItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fallguys_match_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AIItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIItem) ProtoMessage() {}

func (x *AIItem) ProtoReflect() protoreflect.Message {
	mi := &file_fallguys_match_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIItem.ProtoReflect.Descriptor instead.
func (*AIItem) Descriptor() ([]byte, []int) {
	return file_fallguys_match_proto_rawDescGZIP(), []int{16}
}

func (x *AIItem) GetBornPos() string {
	if x != nil {
		return x.BornPos
	}
	return ""
}

func (x *AIItem) GetAiUrl() string {
	if x != nil {
		return x.AiUrl
	}
	return ""
}

type AIList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LowList  []*AIItem `protobuf:"bytes,1,rep,name=low_list,json=lowList,proto3" json:"low_list,omitempty"`    // 低等ai列表
	MidList  []*AIItem `protobuf:"bytes,2,rep,name=mid_list,json=midList,proto3" json:"mid_list,omitempty"`    // 中等ai列表
	HighList []*AIItem `protobuf:"bytes,3,rep,name=high_list,json=highList,proto3" json:"high_list,omitempty"` // 高等ai列表
}

func (x *AIList) Reset() {
	*x = AIList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fallguys_match_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AIList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIList) ProtoMessage() {}

func (x *AIList) ProtoReflect() protoreflect.Message {
	mi := &file_fallguys_match_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIList.ProtoReflect.Descriptor instead.
func (*AIList) Descriptor() ([]byte, []int) {
	return file_fallguys_match_proto_rawDescGZIP(), []int{17}
}

func (x *AIList) GetLowList() []*AIItem {
	if x != nil {
		return x.LowList
	}
	return nil
}

func (x *AIList) GetMidList() []*AIItem {
	if x != nil {
		return x.MidList
	}
	return nil
}

func (x *AIList) GetHighList() []*AIItem {
	if x != nil {
		return x.HighList
	}
	return nil
}

type GetAIListRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AiMap map[int32]*AIList `protobuf:"bytes,1,rep,name=ai_map,json=aiMap,proto3" json:"ai_map,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // 每个关卡对应的ai列表
}

func (x *GetAIListRsp) Reset() {
	*x = GetAIListRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fallguys_match_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAIListRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAIListRsp) ProtoMessage() {}

func (x *GetAIListRsp) ProtoReflect() protoreflect.Message {
	mi := &file_fallguys_match_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAIListRsp.ProtoReflect.Descriptor instead.
func (*GetAIListRsp) Descriptor() ([]byte, []int) {
	return file_fallguys_match_proto_rawDescGZIP(), []int{18}
}

func (x *GetAIListRsp) GetAiMap() map[int32]*AIList {
	if x != nil {
		return x.AiMap
	}
	return nil
}

var File_fallguys_match_proto protoreflect.FileDescriptor

var file_fallguys_match_proto_rawDesc = []byte{
	0x0a, 0x14, 0x66, 0x61, 0x6c, 0x6c, 0x67, 0x75, 0x79, 0x73, 0x2f, 0x6d, 0x61, 0x74, 0x63, 0x68,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x66, 0x61, 0x6c, 0x6c, 0x67, 0x75, 0x79, 0x73,
	0x1a, 0x13, 0x66, 0x61, 0x6c, 0x6c, 0x67, 0x75, 0x79, 0x73, 0x2f, 0x70, 0x75, 0x73, 0x68, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x81, 0x01, 0x0a, 0x0c, 0x53, 0x79, 0x6e, 0x63, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x70, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x6d, 0x6f,
	0x64, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0b, 0x6d, 0x6f, 0x64, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x29, 0x0a, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x66, 0x61,
	0x6c, 0x6c, 0x67, 0x75, 0x79, 0x73, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x0e, 0x0a, 0x0c, 0x53, 0x79, 0x6e, 0x63, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x52, 0x73, 0x70, 0x22, 0x2e, 0x0a, 0x06, 0x57, 0x69, 0x6e, 0x6e, 0x65,
	0x72, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x75, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x22, 0x5e, 0x0a, 0x0a, 0x45, 0x6e, 0x64, 0x47, 0x61,
	0x6d, 0x65, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x72, 0x69, 0x64, 0x12, 0x2a, 0x0a, 0x07, 0x77,
	0x69, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x66,
	0x61, 0x6c, 0x6c, 0x67, 0x75, 0x79, 0x73, 0x2e, 0x57, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x07,
	0x77, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x22, 0x0c, 0x0a, 0x0a, 0x45, 0x6e, 0x64, 0x47, 0x61,
	0x6d, 0x65, 0x52, 0x73, 0x70, 0x22, 0x22, 0x0a, 0x0c, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69,
	0x62, 0x65, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x22, 0x68, 0x0a, 0x0c, 0x53, 0x75, 0x62,
	0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x73, 0x70, 0x12, 0x2e, 0x0a, 0x08, 0x70, 0x75, 0x73,
	0x68, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x66, 0x61,
	0x6c, 0x6c, 0x67, 0x75, 0x79, 0x73, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x08, 0x70, 0x75, 0x73, 0x68, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a,
	0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x73,
	0x67, 0x49, 0x64, 0x22, 0x75, 0x0a, 0x0c, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x61, 0x64, 0x79,
	0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x61, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x05, 0x72, 0x65, 0x61, 0x64, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x73, 0x67,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61,
	0x64, 0x64, 0x72, 0x12, 0x13, 0x0a, 0x05, 0x64, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x64, 0x73, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x69, 0x64, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x72, 0x69, 0x64, 0x22, 0x0e, 0x0a, 0x0c, 0x47, 0x61,
	0x6d, 0x65, 0x52, 0x65, 0x61, 0x64, 0x79, 0x52, 0x73, 0x70, 0x22, 0x9e, 0x01, 0x0a, 0x0b, 0x45,
	0x6e, 0x64, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64,
	0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x12, 0x10,
	0x0a, 0x03, 0x72, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x72, 0x69, 0x64,
	0x12, 0x2a, 0x0a, 0x07, 0x77, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x66, 0x61, 0x6c, 0x6c, 0x67, 0x75, 0x79, 0x73, 0x2e, 0x57, 0x69, 0x6e,
	0x6e, 0x65, 0x72, 0x52, 0x07, 0x77, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x12, 0x20, 0x0a, 0x0b,
	0x69, 0x73, 0x4c, 0x61, 0x73, 0x74, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0b, 0x69, 0x73, 0x4c, 0x61, 0x73, 0x74, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x1b,
	0x0a, 0x09, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x4e, 0x75, 0x6d, 0x22, 0x41, 0x0a, 0x0b, 0x45,
	0x6e, 0x64, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x52, 0x73, 0x70, 0x12, 0x32, 0x0a, 0x07, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x66, 0x61,
	0x6c, 0x6c, 0x67, 0x75, 0x79, 0x73, 0x2e, 0x45, 0x6e, 0x64, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x22, 0x59,
	0x0a, 0x0e, 0x45, 0x6e, 0x64, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75,
	0x69, 0x64, 0x12, 0x35, 0x0a, 0x0b, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x5f, 0x6c, 0x69, 0x73,
	0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x66, 0x61, 0x6c, 0x6c, 0x67, 0x75,
	0x79, 0x73, 0x2e, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x0a, 0x72,
	0x65, 0x77, 0x61, 0x72, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x76, 0x0a, 0x0a, 0x52, 0x65, 0x77,
	0x61, 0x72, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x69,
	0x74, 0x65, 0x6d, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x69, 0x74, 0x65,
	0x6d, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x6e, 0x75, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x6d, 0x67,
	0x75, 0x72, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x6d, 0x67, 0x75, 0x72,
	0x6c, 0x22, 0xc6, 0x01, 0x0a, 0x0f, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x65, 0x74, 0x72,
	0x69, 0x63, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a,
	0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12,
	0x10, 0x0a, 0x03, 0x72, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x72, 0x69,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x16, 0x0a,
	0x06, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d,
	0x61, 0x72, 0x6b, 0x65, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x29, 0x0a, 0x03, 0x6b, 0x76, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53,
	0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x03, 0x6b, 0x76, 0x73, 0x22, 0x11, 0x0a, 0x0f, 0x55, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x52, 0x73, 0x71, 0x22, 0xb0, 0x01,
	0x0a, 0x0c, 0x47, 0x65, 0x74, 0x41, 0x49, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x10,
	0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6e, 0x75, 0x6d,
	0x12, 0x4d, 0x0a, 0x0d, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x66, 0x61, 0x6c, 0x6c, 0x67, 0x75,
	0x79, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x49, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x2e,
	0x4c, 0x65, 0x76, 0x65, 0x6c, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x0c, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x1a,
	0x3f, 0x0a, 0x11, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x22, 0x3a, 0x0a, 0x06, 0x41, 0x49, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x6f,
	0x72, 0x6e, 0x5f, 0x70, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x6f,
	0x72, 0x6e, 0x50, 0x6f, 0x73, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x69, 0x5f, 0x75, 0x72, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x69, 0x55, 0x72, 0x6c, 0x22, 0x91, 0x01, 0x0a,
	0x06, 0x41, 0x49, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x08, 0x6c, 0x6f, 0x77, 0x5f, 0x6c,
	0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x66, 0x61, 0x6c, 0x6c,
	0x67, 0x75, 0x79, 0x73, 0x2e, 0x41, 0x49, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x07, 0x6c, 0x6f, 0x77,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x08, 0x6d, 0x69, 0x64, 0x5f, 0x6c, 0x69, 0x73, 0x74,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x66, 0x61, 0x6c, 0x6c, 0x67, 0x75, 0x79,
	0x73, 0x2e, 0x41, 0x49, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x07, 0x6d, 0x69, 0x64, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x2d, 0x0a, 0x09, 0x68, 0x69, 0x67, 0x68, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x66, 0x61, 0x6c, 0x6c, 0x67, 0x75, 0x79, 0x73, 0x2e,
	0x41, 0x49, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x08, 0x68, 0x69, 0x67, 0x68, 0x4c, 0x69, 0x73, 0x74,
	0x22, 0x94, 0x01, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x41, 0x49, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x73,
	0x70, 0x12, 0x38, 0x0a, 0x06, 0x61, 0x69, 0x5f, 0x6d, 0x61, 0x70, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x21, 0x2e, 0x66, 0x61, 0x6c, 0x6c, 0x67, 0x75, 0x79, 0x73, 0x2e, 0x47, 0x65, 0x74,
	0x41, 0x49, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x73, 0x70, 0x2e, 0x41, 0x69, 0x4d, 0x61, 0x70, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x61, 0x69, 0x4d, 0x61, 0x70, 0x1a, 0x4a, 0x0a, 0x0a, 0x41,
	0x69, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x26, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x66, 0x61, 0x6c,
	0x6c, 0x67, 0x75, 0x79, 0x73, 0x2e, 0x41, 0x49, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x2a, 0x4b, 0x0a, 0x09, 0x52, 0x6f, 0x6f, 0x6d, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x49, 0x64, 0x6c, 0x65, 0x10, 0x00, 0x12, 0x0d,
	0x0a, 0x09, 0x57, 0x61, 0x69, 0x74, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x10, 0x01, 0x12, 0x0a, 0x0a,
	0x06, 0x49, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x57, 0x61, 0x69,
	0x74, 0x45, 0x78, 0x69, 0x74, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x4f, 0x66, 0x66, 0x6c, 0x69,
	0x6e, 0x65, 0x10, 0x04, 0x32, 0xca, 0x03, 0x0a, 0x0b, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x12, 0x3d, 0x0a, 0x09, 0x53, 0x79, 0x6e, 0x63, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x12, 0x16, 0x2e, 0x66, 0x61, 0x6c, 0x6c, 0x67, 0x75, 0x79, 0x73, 0x2e, 0x53, 0x79, 0x6e,
	0x63, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x66, 0x61, 0x6c, 0x6c,
	0x67, 0x75, 0x79, 0x73, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x73,
	0x70, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x07, 0x45, 0x6e, 0x64, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x14,
	0x2e, 0x66, 0x61, 0x6c, 0x6c, 0x67, 0x75, 0x79, 0x73, 0x2e, 0x45, 0x6e, 0x64, 0x47, 0x61, 0x6d,
	0x65, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x66, 0x61, 0x6c, 0x6c, 0x67, 0x75, 0x79, 0x73, 0x2e,
	0x45, 0x6e, 0x64, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x73, 0x70, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x09,
	0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x61, 0x64, 0x79, 0x12, 0x16, 0x2e, 0x66, 0x61, 0x6c, 0x6c,
	0x67, 0x75, 0x79, 0x73, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x61, 0x64, 0x79, 0x52, 0x65,
	0x71, 0x1a, 0x16, 0x2e, 0x66, 0x61, 0x6c, 0x6c, 0x67, 0x75, 0x79, 0x73, 0x2e, 0x47, 0x61, 0x6d,
	0x65, 0x52, 0x65, 0x61, 0x64, 0x79, 0x52, 0x73, 0x70, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x09, 0x53,
	0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x12, 0x16, 0x2e, 0x66, 0x61, 0x6c, 0x6c, 0x67,
	0x75, 0x79, 0x73, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x71,
	0x1a, 0x16, 0x2e, 0x66, 0x61, 0x6c, 0x6c, 0x67, 0x75, 0x79, 0x73, 0x2e, 0x53, 0x75, 0x62, 0x73,
	0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x73, 0x70, 0x22, 0x00, 0x30, 0x01, 0x12, 0x3a, 0x0a, 0x08,
	0x45, 0x6e, 0x64, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x15, 0x2e, 0x66, 0x61, 0x6c, 0x6c, 0x67,
	0x75, 0x79, 0x73, 0x2e, 0x45, 0x6e, 0x64, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x1a,
	0x15, 0x2e, 0x66, 0x61, 0x6c, 0x6c, 0x67, 0x75, 0x79, 0x73, 0x2e, 0x45, 0x6e, 0x64, 0x52, 0x6f,
	0x75, 0x6e, 0x64, 0x52, 0x73, 0x70, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x0c, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x12, 0x19, 0x2e, 0x66, 0x61, 0x6c, 0x6c, 0x67,
	0x75, 0x79, 0x73, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63,
	0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x66, 0x61, 0x6c, 0x6c, 0x67, 0x75, 0x79, 0x73, 0x2e, 0x55,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x52, 0x73, 0x71, 0x22, 0x00,
	0x28, 0x01, 0x12, 0x3d, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x41, 0x49, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x16, 0x2e, 0x66, 0x61, 0x6c, 0x6c, 0x67, 0x75, 0x79, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x49,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x66, 0x61, 0x6c, 0x6c, 0x67, 0x75,
	0x79, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x49, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x73, 0x70, 0x22,
	0x00, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x2e, 0x31, 0x37, 0x7a, 0x6a, 0x68, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x73, 0x6e, 0x61, 0x6b, 0x65, 0x2f, 0x73, 0x6e, 0x61, 0x6b, 0x65, 0x5f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x61, 0x6c, 0x6c, 0x67, 0x75, 0x79, 0x73, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_fallguys_match_proto_rawDescOnce sync.Once
	file_fallguys_match_proto_rawDescData = file_fallguys_match_proto_rawDesc
)

func file_fallguys_match_proto_rawDescGZIP() []byte {
	file_fallguys_match_proto_rawDescOnce.Do(func() {
		file_fallguys_match_proto_rawDescData = protoimpl.X.CompressGZIP(file_fallguys_match_proto_rawDescData)
	})
	return file_fallguys_match_proto_rawDescData
}

var file_fallguys_match_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_fallguys_match_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_fallguys_match_proto_goTypes = []interface{}{
	(RoomState)(0),          // 0: fallguys.RoomState
	(*SyncStateReq)(nil),    // 1: fallguys.SyncStateReq
	(*SyncStateRsp)(nil),    // 2: fallguys.SyncStateRsp
	(*Winner)(nil),          // 3: fallguys.Winner
	(*EndGameReq)(nil),      // 4: fallguys.EndGameReq
	(*EndGameRsp)(nil),      // 5: fallguys.EndGameRsp
	(*SubscribeReq)(nil),    // 6: fallguys.SubscribeReq
	(*SubscribeRsp)(nil),    // 7: fallguys.SubscribeRsp
	(*GameReadyReq)(nil),    // 8: fallguys.GameReadyReq
	(*GameReadyRsp)(nil),    // 9: fallguys.GameReadyRsp
	(*EndRoundReq)(nil),     // 10: fallguys.EndRoundReq
	(*EndRoundRsp)(nil),     // 11: fallguys.EndRoundRsp
	(*EndRoundPlayer)(nil),  // 12: fallguys.EndRoundPlayer
	(*RewardItem)(nil),      // 13: fallguys.RewardItem
	(*UploadMetricReq)(nil), // 14: fallguys.UploadMetricReq
	(*UploadMetricRsq)(nil), // 15: fallguys.UploadMetricRsq
	(*GetAIListReq)(nil),    // 16: fallguys.GetAIListReq
	(*AIItem)(nil),          // 17: fallguys.AIItem
	(*AIList)(nil),          // 18: fallguys.AIList
	(*GetAIListRsp)(nil),    // 19: fallguys.GetAIListRsp
	nil,                     // 20: fallguys.GetAIListReq.LevelVersionEntry
	nil,                     // 21: fallguys.GetAIListRsp.AiMapEntry
	(PushType)(0),           // 22: fallguys.PushType
	(*structpb.Struct)(nil), // 23: google.protobuf.Struct
}
var file_fallguys_match_proto_depIdxs = []int32{
	0,  // 0: fallguys.SyncStateReq.state:type_name -> fallguys.RoomState
	3,  // 1: fallguys.EndGameReq.winners:type_name -> fallguys.Winner
	22, // 2: fallguys.SubscribeRsp.pushType:type_name -> fallguys.PushType
	3,  // 3: fallguys.EndRoundReq.winners:type_name -> fallguys.Winner
	12, // 4: fallguys.EndRoundRsp.players:type_name -> fallguys.EndRoundPlayer
	13, // 5: fallguys.EndRoundPlayer.reward_list:type_name -> fallguys.RewardItem
	23, // 6: fallguys.UploadMetricReq.kvs:type_name -> google.protobuf.Struct
	20, // 7: fallguys.GetAIListReq.level_version:type_name -> fallguys.GetAIListReq.LevelVersionEntry
	17, // 8: fallguys.AIList.low_list:type_name -> fallguys.AIItem
	17, // 9: fallguys.AIList.mid_list:type_name -> fallguys.AIItem
	17, // 10: fallguys.AIList.high_list:type_name -> fallguys.AIItem
	21, // 11: fallguys.GetAIListRsp.ai_map:type_name -> fallguys.GetAIListRsp.AiMapEntry
	18, // 12: fallguys.GetAIListRsp.AiMapEntry.value:type_name -> fallguys.AIList
	1,  // 13: fallguys.MatchServer.SyncState:input_type -> fallguys.SyncStateReq
	4,  // 14: fallguys.MatchServer.EndGame:input_type -> fallguys.EndGameReq
	8,  // 15: fallguys.MatchServer.GameReady:input_type -> fallguys.GameReadyReq
	6,  // 16: fallguys.MatchServer.Subscribe:input_type -> fallguys.SubscribeReq
	10, // 17: fallguys.MatchServer.EndRound:input_type -> fallguys.EndRoundReq
	14, // 18: fallguys.MatchServer.UploadMetric:input_type -> fallguys.UploadMetricReq
	16, // 19: fallguys.MatchServer.GetAIList:input_type -> fallguys.GetAIListReq
	2,  // 20: fallguys.MatchServer.SyncState:output_type -> fallguys.SyncStateRsp
	5,  // 21: fallguys.MatchServer.EndGame:output_type -> fallguys.EndGameRsp
	9,  // 22: fallguys.MatchServer.GameReady:output_type -> fallguys.GameReadyRsp
	7,  // 23: fallguys.MatchServer.Subscribe:output_type -> fallguys.SubscribeRsp
	11, // 24: fallguys.MatchServer.EndRound:output_type -> fallguys.EndRoundRsp
	15, // 25: fallguys.MatchServer.UploadMetric:output_type -> fallguys.UploadMetricRsq
	19, // 26: fallguys.MatchServer.GetAIList:output_type -> fallguys.GetAIListRsp
	20, // [20:27] is the sub-list for method output_type
	13, // [13:20] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_fallguys_match_proto_init() }
func file_fallguys_match_proto_init() {
	if File_fallguys_match_proto != nil {
		return
	}
	file_fallguys_push_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_fallguys_match_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncStateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fallguys_match_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncStateRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fallguys_match_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Winner); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fallguys_match_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EndGameReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fallguys_match_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EndGameRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fallguys_match_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscribeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fallguys_match_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscribeRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fallguys_match_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameReadyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fallguys_match_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameReadyRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fallguys_match_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EndRoundReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fallguys_match_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EndRoundRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fallguys_match_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EndRoundPlayer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fallguys_match_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RewardItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fallguys_match_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadMetricReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fallguys_match_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadMetricRsq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fallguys_match_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAIListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fallguys_match_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AIItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fallguys_match_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AIList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fallguys_match_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAIListRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fallguys_match_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fallguys_match_proto_goTypes,
		DependencyIndexes: file_fallguys_match_proto_depIdxs,
		EnumInfos:         file_fallguys_match_proto_enumTypes,
		MessageInfos:      file_fallguys_match_proto_msgTypes,
	}.Build()
	File_fallguys_match_proto = out.File
	file_fallguys_match_proto_rawDesc = nil
	file_fallguys_match_proto_goTypes = nil
	file_fallguys_match_proto_depIdxs = nil
}
