// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: fallguys/match.proto

package fallguys

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	MatchServer_SyncState_FullMethodName    = "/fallguys.MatchServer/SyncState"
	MatchServer_EndGame_FullMethodName      = "/fallguys.MatchServer/EndGame"
	MatchServer_GameReady_FullMethodName    = "/fallguys.MatchServer/GameReady"
	MatchServer_Subscribe_FullMethodName    = "/fallguys.MatchServer/Subscribe"
	MatchServer_EndRound_FullMethodName     = "/fallguys.MatchServer/EndRound"
	MatchServer_UploadMetric_FullMethodName = "/fallguys.MatchServer/UploadMetric"
	MatchServer_GetAIList_FullMethodName    = "/fallguys.MatchServer/GetAIList"
)

// MatchServerClient is the client API for MatchServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MatchServerClient interface {
	SyncState(ctx context.Context, in *SyncStateReq, opts ...grpc.CallOption) (*SyncStateRsp, error)
	EndGame(ctx context.Context, in *EndGameReq, opts ...grpc.CallOption) (*EndGameRsp, error)
	GameReady(ctx context.Context, in *GameReadyReq, opts ...grpc.CallOption) (*GameReadyRsp, error)
	Subscribe(ctx context.Context, in *SubscribeReq, opts ...grpc.CallOption) (MatchServer_SubscribeClient, error)
	EndRound(ctx context.Context, in *EndRoundReq, opts ...grpc.CallOption) (*EndRoundRsp, error)
	UploadMetric(ctx context.Context, opts ...grpc.CallOption) (MatchServer_UploadMetricClient, error)
	GetAIList(ctx context.Context, in *GetAIListReq, opts ...grpc.CallOption) (*GetAIListRsp, error)
}

type matchServerClient struct {
	cc grpc.ClientConnInterface
}

func NewMatchServerClient(cc grpc.ClientConnInterface) MatchServerClient {
	return &matchServerClient{cc}
}

func (c *matchServerClient) SyncState(ctx context.Context, in *SyncStateReq, opts ...grpc.CallOption) (*SyncStateRsp, error) {
	out := new(SyncStateRsp)
	err := c.cc.Invoke(ctx, MatchServer_SyncState_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchServerClient) EndGame(ctx context.Context, in *EndGameReq, opts ...grpc.CallOption) (*EndGameRsp, error) {
	out := new(EndGameRsp)
	err := c.cc.Invoke(ctx, MatchServer_EndGame_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchServerClient) GameReady(ctx context.Context, in *GameReadyReq, opts ...grpc.CallOption) (*GameReadyRsp, error) {
	out := new(GameReadyRsp)
	err := c.cc.Invoke(ctx, MatchServer_GameReady_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchServerClient) Subscribe(ctx context.Context, in *SubscribeReq, opts ...grpc.CallOption) (MatchServer_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &MatchServer_ServiceDesc.Streams[0], MatchServer_Subscribe_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &matchServerSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MatchServer_SubscribeClient interface {
	Recv() (*SubscribeRsp, error)
	grpc.ClientStream
}

type matchServerSubscribeClient struct {
	grpc.ClientStream
}

func (x *matchServerSubscribeClient) Recv() (*SubscribeRsp, error) {
	m := new(SubscribeRsp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *matchServerClient) EndRound(ctx context.Context, in *EndRoundReq, opts ...grpc.CallOption) (*EndRoundRsp, error) {
	out := new(EndRoundRsp)
	err := c.cc.Invoke(ctx, MatchServer_EndRound_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchServerClient) UploadMetric(ctx context.Context, opts ...grpc.CallOption) (MatchServer_UploadMetricClient, error) {
	stream, err := c.cc.NewStream(ctx, &MatchServer_ServiceDesc.Streams[1], MatchServer_UploadMetric_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &matchServerUploadMetricClient{stream}
	return x, nil
}

type MatchServer_UploadMetricClient interface {
	Send(*UploadMetricReq) error
	CloseAndRecv() (*UploadMetricRsq, error)
	grpc.ClientStream
}

type matchServerUploadMetricClient struct {
	grpc.ClientStream
}

func (x *matchServerUploadMetricClient) Send(m *UploadMetricReq) error {
	return x.ClientStream.SendMsg(m)
}

func (x *matchServerUploadMetricClient) CloseAndRecv() (*UploadMetricRsq, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(UploadMetricRsq)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *matchServerClient) GetAIList(ctx context.Context, in *GetAIListReq, opts ...grpc.CallOption) (*GetAIListRsp, error) {
	out := new(GetAIListRsp)
	err := c.cc.Invoke(ctx, MatchServer_GetAIList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MatchServerServer is the server API for MatchServer service.
// All implementations should embed UnimplementedMatchServerServer
// for forward compatibility
type MatchServerServer interface {
	SyncState(context.Context, *SyncStateReq) (*SyncStateRsp, error)
	EndGame(context.Context, *EndGameReq) (*EndGameRsp, error)
	GameReady(context.Context, *GameReadyReq) (*GameReadyRsp, error)
	Subscribe(*SubscribeReq, MatchServer_SubscribeServer) error
	EndRound(context.Context, *EndRoundReq) (*EndRoundRsp, error)
	UploadMetric(MatchServer_UploadMetricServer) error
	GetAIList(context.Context, *GetAIListReq) (*GetAIListRsp, error)
}

// UnimplementedMatchServerServer should be embedded to have forward compatible implementations.
type UnimplementedMatchServerServer struct {
}

func (UnimplementedMatchServerServer) SyncState(context.Context, *SyncStateReq) (*SyncStateRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncState not implemented")
}
func (UnimplementedMatchServerServer) EndGame(context.Context, *EndGameReq) (*EndGameRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EndGame not implemented")
}
func (UnimplementedMatchServerServer) GameReady(context.Context, *GameReadyReq) (*GameReadyRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GameReady not implemented")
}
func (UnimplementedMatchServerServer) Subscribe(*SubscribeReq, MatchServer_SubscribeServer) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedMatchServerServer) EndRound(context.Context, *EndRoundReq) (*EndRoundRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EndRound not implemented")
}
func (UnimplementedMatchServerServer) UploadMetric(MatchServer_UploadMetricServer) error {
	return status.Errorf(codes.Unimplemented, "method UploadMetric not implemented")
}
func (UnimplementedMatchServerServer) GetAIList(context.Context, *GetAIListReq) (*GetAIListRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAIList not implemented")
}

// UnsafeMatchServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MatchServerServer will
// result in compilation errors.
type UnsafeMatchServerServer interface {
	mustEmbedUnimplementedMatchServerServer()
}

func RegisterMatchServerServer(s grpc.ServiceRegistrar, srv MatchServerServer) {
	s.RegisterService(&MatchServer_ServiceDesc, srv)
}

func _MatchServer_SyncState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncStateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchServerServer).SyncState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchServer_SyncState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchServerServer).SyncState(ctx, req.(*SyncStateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchServer_EndGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndGameReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchServerServer).EndGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchServer_EndGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchServerServer).EndGame(ctx, req.(*EndGameReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchServer_GameReady_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GameReadyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchServerServer).GameReady(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchServer_GameReady_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchServerServer).GameReady(ctx, req.(*GameReadyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchServer_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MatchServerServer).Subscribe(m, &matchServerSubscribeServer{stream})
}

type MatchServer_SubscribeServer interface {
	Send(*SubscribeRsp) error
	grpc.ServerStream
}

type matchServerSubscribeServer struct {
	grpc.ServerStream
}

func (x *matchServerSubscribeServer) Send(m *SubscribeRsp) error {
	return x.ServerStream.SendMsg(m)
}

func _MatchServer_EndRound_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndRoundReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchServerServer).EndRound(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchServer_EndRound_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchServerServer).EndRound(ctx, req.(*EndRoundReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchServer_UploadMetric_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MatchServerServer).UploadMetric(&matchServerUploadMetricServer{stream})
}

type MatchServer_UploadMetricServer interface {
	SendAndClose(*UploadMetricRsq) error
	Recv() (*UploadMetricReq, error)
	grpc.ServerStream
}

type matchServerUploadMetricServer struct {
	grpc.ServerStream
}

func (x *matchServerUploadMetricServer) SendAndClose(m *UploadMetricRsq) error {
	return x.ServerStream.SendMsg(m)
}

func (x *matchServerUploadMetricServer) Recv() (*UploadMetricReq, error) {
	m := new(UploadMetricReq)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _MatchServer_GetAIList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAIListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchServerServer).GetAIList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchServer_GetAIList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchServerServer).GetAIList(ctx, req.(*GetAIListReq))
	}
	return interceptor(ctx, in, info, handler)
}

// MatchServer_ServiceDesc is the grpc.ServiceDesc for MatchServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MatchServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fallguys.MatchServer",
	HandlerType: (*MatchServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SyncState",
			Handler:    _MatchServer_SyncState_Handler,
		},
		{
			MethodName: "EndGame",
			Handler:    _MatchServer_EndGame_Handler,
		},
		{
			MethodName: "GameReady",
			Handler:    _MatchServer_GameReady_Handler,
		},
		{
			MethodName: "EndRound",
			Handler:    _MatchServer_EndRound_Handler,
		},
		{
			MethodName: "GetAIList",
			Handler:    _MatchServer_GetAIList_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _MatchServer_Subscribe_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "UploadMetric",
			Handler:       _MatchServer_UploadMetric_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "fallguys/match.proto",
}
