// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.16.1
// source: fallguys/push.proto

package fallguys

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PushType int32

const (
	PushType_SyncGameInfo PushType = 0 //初始化房间
)

// Enum value maps for PushType.
var (
	PushType_name = map[int32]string{
		0: "SyncGameInfo",
	}
	PushType_value = map[string]int32{
		"SyncGameInfo": 0,
	}
)

func (x PushType) Enum() *PushType {
	p := new(PushType)
	*p = x
	return p
}

func (x PushType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PushType) Descriptor() protoreflect.EnumDescriptor {
	return file_fallguys_push_proto_enumTypes[0].Descriptor()
}

func (PushType) Type() protoreflect.EnumType {
	return &file_fallguys_push_proto_enumTypes[0]
}

func (x PushType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PushType.Descriptor instead.
func (PushType) EnumDescriptor() ([]byte, []int) {
	return file_fallguys_push_proto_rawDescGZIP(), []int{0}
}

//玩家类型
type PlayerType int32

const (
	PlayerType_InvalidPlayer PlayerType = 0 //占位
	PlayerType_Real          PlayerType = 1 //真人
	PlayerType_Ai            PlayerType = 2 // ai
)

// Enum value maps for PlayerType.
var (
	PlayerType_name = map[int32]string{
		0: "InvalidPlayer",
		1: "Real",
		2: "Ai",
	}
	PlayerType_value = map[string]int32{
		"InvalidPlayer": 0,
		"Real":          1,
		"Ai":            2,
	}
)

func (x PlayerType) Enum() *PlayerType {
	p := new(PlayerType)
	*p = x
	return p
}

func (x PlayerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerType) Descriptor() protoreflect.EnumDescriptor {
	return file_fallguys_push_proto_enumTypes[1].Descriptor()
}

func (PlayerType) Type() protoreflect.EnumType {
	return &file_fallguys_push_proto_enumTypes[1]
}

func (x PlayerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerType.Descriptor instead.
func (PlayerType) EnumDescriptor() ([]byte, []int) {
	return file_fallguys_push_proto_rawDescGZIP(), []int{1}
}

type PlayerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid        string     `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`                                         //玩家uid
	PlayerType PlayerType `protobuf:"varint,2,opt,name=playerType,proto3,enum=fallguys.PlayerType" json:"playerType,omitempty"` //玩家类型
}

func (x *PlayerInfo) Reset() {
	*x = PlayerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fallguys_push_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInfo) ProtoMessage() {}

func (x *PlayerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_fallguys_push_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInfo.ProtoReflect.Descriptor instead.
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return file_fallguys_push_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerInfo) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *PlayerInfo) GetPlayerType() PlayerType {
	if x != nil {
		return x.PlayerType
	}
	return PlayerType_InvalidPlayer
}

// TCPServer 向UnityServer同步房间信息
type PuSyncGameInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GamMode   int32         `protobuf:"zigzag32,1,opt,name=gamMode,proto3" json:"gamMode,omitempty"`   //游戏模式,903 糖豆人大逃杀，904 大逃杀娱乐
	PlayerCnt int32         `protobuf:"varint,2,opt,name=playerCnt,proto3" json:"playerCnt,omitempty"` //玩家数量
	Players   []*PlayerInfo `protobuf:"bytes,3,rep,name=players,proto3" json:"players,omitempty"`      //玩家信息
	Rid       int32         `protobuf:"varint,4,opt,name=rid,proto3" json:"rid,omitempty"`             // 房间id
}

func (x *PuSyncGameInfo) Reset() {
	*x = PuSyncGameInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fallguys_push_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PuSyncGameInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PuSyncGameInfo) ProtoMessage() {}

func (x *PuSyncGameInfo) ProtoReflect() protoreflect.Message {
	mi := &file_fallguys_push_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PuSyncGameInfo.ProtoReflect.Descriptor instead.
func (*PuSyncGameInfo) Descriptor() ([]byte, []int) {
	return file_fallguys_push_proto_rawDescGZIP(), []int{1}
}

func (x *PuSyncGameInfo) GetGamMode() int32 {
	if x != nil {
		return x.GamMode
	}
	return 0
}

func (x *PuSyncGameInfo) GetPlayerCnt() int32 {
	if x != nil {
		return x.PlayerCnt
	}
	return 0
}

func (x *PuSyncGameInfo) GetPlayers() []*PlayerInfo {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *PuSyncGameInfo) GetRid() int32 {
	if x != nil {
		return x.Rid
	}
	return 0
}

var File_fallguys_push_proto protoreflect.FileDescriptor

var file_fallguys_push_proto_rawDesc = []byte{
	0x0a, 0x13, 0x66, 0x61, 0x6c, 0x6c, 0x67, 0x75, 0x79, 0x73, 0x2f, 0x70, 0x75, 0x73, 0x68, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x66, 0x61, 0x6c, 0x6c, 0x67, 0x75, 0x79, 0x73, 0x22,
	0x54, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a,
	0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12,
	0x34, 0x0a, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x66, 0x61, 0x6c, 0x6c, 0x67, 0x75, 0x79, 0x73, 0x2e, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x54, 0x79, 0x70, 0x65, 0x22, 0x8a, 0x01, 0x0a, 0x0e, 0x50, 0x75, 0x53, 0x79, 0x6e, 0x63,
	0x47, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x61, 0x6d, 0x4d,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x11, 0x52, 0x07, 0x67, 0x61, 0x6d, 0x4d, 0x6f,
	0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x6e, 0x74,
	0x12, 0x2e, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x66, 0x61, 0x6c, 0x6c, 0x67, 0x75, 0x79, 0x73, 0x2e, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73,
	0x12, 0x10, 0x0a, 0x03, 0x72, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x72,
	0x69, 0x64, 0x2a, 0x1c, 0x0a, 0x08, 0x50, 0x75, 0x73, 0x68, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10,
	0x0a, 0x0c, 0x53, 0x79, 0x6e, 0x63, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x10, 0x00,
	0x2a, 0x31, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x11,
	0x0a, 0x0d, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x10,
	0x00, 0x12, 0x08, 0x0a, 0x04, 0x52, 0x65, 0x61, 0x6c, 0x10, 0x01, 0x12, 0x06, 0x0a, 0x02, 0x41,
	0x69, 0x10, 0x02, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x2e, 0x31, 0x37, 0x7a, 0x6a, 0x68,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x6e, 0x61, 0x6b, 0x65, 0x2f, 0x73, 0x6e, 0x61, 0x6b, 0x65,
	0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x61, 0x6c, 0x6c, 0x67, 0x75, 0x79, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_fallguys_push_proto_rawDescOnce sync.Once
	file_fallguys_push_proto_rawDescData = file_fallguys_push_proto_rawDesc
)

func file_fallguys_push_proto_rawDescGZIP() []byte {
	file_fallguys_push_proto_rawDescOnce.Do(func() {
		file_fallguys_push_proto_rawDescData = protoimpl.X.CompressGZIP(file_fallguys_push_proto_rawDescData)
	})
	return file_fallguys_push_proto_rawDescData
}

var file_fallguys_push_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_fallguys_push_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_fallguys_push_proto_goTypes = []interface{}{
	(PushType)(0),          // 0: fallguys.PushType
	(PlayerType)(0),        // 1: fallguys.PlayerType
	(*PlayerInfo)(nil),     // 2: fallguys.PlayerInfo
	(*PuSyncGameInfo)(nil), // 3: fallguys.PuSyncGameInfo
}
var file_fallguys_push_proto_depIdxs = []int32{
	1, // 0: fallguys.PlayerInfo.playerType:type_name -> fallguys.PlayerType
	2, // 1: fallguys.PuSyncGameInfo.players:type_name -> fallguys.PlayerInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_fallguys_push_proto_init() }
func file_fallguys_push_proto_init() {
	if File_fallguys_push_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_fallguys_push_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fallguys_push_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PuSyncGameInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fallguys_push_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fallguys_push_proto_goTypes,
		DependencyIndexes: file_fallguys_push_proto_depIdxs,
		EnumInfos:         file_fallguys_push_proto_enumTypes,
		MessageInfos:      file_fallguys_push_proto_msgTypes,
	}.Build()
	File_fallguys_push_proto = out.File
	file_fallguys_push_proto_rawDesc = nil
	file_fallguys_push_proto_goTypes = nil
	file_fallguys_push_proto_depIdxs = nil
}
